.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/submit-question.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Removing all `___PROJECT___` references and replacing them with `cuspatial` for links and `cuSpatial` for text/doc references.

[REVIEW] DOC Remove template references and update for cuSpatial

---

python/cuspatial/cuspatial/bindings/query.pxd
python/cuspatial/cuspatial/bindings/query.pyx
python/cuspatial/cuspatial/bindings/soa_readers.pxd
python/cuspatial/cuspatial/bindings/spatial.pxd
python/cuspatial/cuspatial/bindings/trajectory.pxd

These import statements snuck in during a bad merge.

Weirdly missed import statements that are guaranteed to fail.

---

CHANGELOG.md

This defeats the need for $PYTHONPATH :guitar:

Add empty __init__.py files so that package resolution works properly.

---

CHANGELOG.md
cpp/CMakeLists.txt
cpp/tests/CMakeLists.txt
pyproject.toml
python/cuspatial/.flake8.cython
python/cuspatial/setup.cfg
python/cuspatial/setup.py
setup.cfg

[REVIEW] Add cython headers to install, python / cmake packaging cleanup

---

CHANGELOG.md
python/cuspatial/cuspatial/core/gis.py

Add example to point in polygon and scale to haversine distance.

---

CHANGELOG.md
python/cuspatial/cuspatial/core/gis.py
python/cuspatial/cuspatial/tests/test_pip.py
python/cuspatial/cuspatial/utils/gis_utils.py

**Summary of Changes**
- Adds several point-in-polygon related utility functions to a newly created `gis_utils.py`. They are involved in converting the bitmap NumericalColumn result from `cpp_point_in_polygon_bitmap` to a DataFrame. The helper utility functions assume positive-only inputs.
- Updates tests accordingly.
This closes #48 
@thomcom

[REVIEW] Point-in-polygon DataFrame output

---

README.md

added conda install and light restructure to readme.  Closes #52

Update readme to include conda install

---

CHANGELOG.md
ci/cpu/libcuspatial/build_libcuspatial.sh
conda/recipes/libcuspatial/meta.yaml

Use YYMMDD tag in nightly build

---

CHANGELOG.md
ci/cpu/build.sh
ci/cpu/libcuspatial/build_libcuspatial.sh
conda/recipes/cuspatial/meta.yaml

Use YYMMDD tag in nightly build of cuspatial python package

---

CHANGELOG.md
python/cuspatial/cuspatial/core/gis.py
python/cuspatial/cuspatial/core/trajectory.py
python/cuspatial/cuspatial/tests/test_hausdorff_distance.py

Auto-merge triggered by push to `branch-0.10` that creates a PR to keep `branch-0.11` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.10 to branch-0.11 [skip ci]

---

CHANGELOG.md
cpp/src/query/spatial_window_points.cu
cpp/src/spatial/hausdorff.cu
cpp/src/spatial/haversine.cu
cpp/src/spatial/lonlat_to_coordinate.cu
cpp/src/spatial/point_in_polygon.cu
cpp/src/trajectory/derive_trajectories.cu
cpp/src/trajectory/subset_trajectories.cu
cpp/src/trajectory/trajectory_distance_speed.cu
cpp/src/trajectory/trajectory_spatial_bound.cu
cpp/src/utility/trajectory_thrust.cuh

Added includes of new "legacy" cudf headers and other supporting headers in response to recent cudf refactorings.
_Sorry for the noisy diff - my editor automatically removes trailing whitespace. My changes were limited to adding includes._

Updates to accommodate cudf refactoring.

---

CHANGELOG.md
cpp/src/query/spatial_window_points.cu
cpp/src/spatial/hausdorff.cu
cpp/src/spatial/haversine.cu
cpp/src/spatial/lonlat_to_coordinate.cu
cpp/src/spatial/point_in_polygon.cu
cpp/src/trajectory/derive_trajectories.cu
cpp/src/trajectory/subset_trajectories.cu
cpp/src/trajectory/trajectory_distance_speed.cu
cpp/src/trajectory/trajectory_spatial_bound.cu

[REVIEW] updating includes for new cuda_utils.hpp location

---

CHANGELOG.md

Branch 0.12 manual merge

---

CHANGELOG.md
python/cuspatial/cuspatial/io/shapefile.py

The python layer for shapefile reader was incorrect, this handles the error.
Fixes #111

Tweak to shapefile.py to properly return the results.

---

CHANGELOG.md
python/cuspatial/cuspatial/io/shapefile.py

Auto-merge triggered by push to `branch-0.12` that creates a PR to keep `branch-0.13` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.12 to branch-0.13 [skip ci]

---

CHANGELOG.md
python/cuspatial/cuspatial/utils/gis_utils.py

Instead of using RMM's `device_array`, which is planned to go away ( https://github.com/rapidsai/rmm/issues/180 ), switch to using RMM's `DeviceBuffer`. Since this already supports `__cuda_array_interface__`, it's straightforward to get a Numba array that views the allocation. From there only a little work is needed to cast it to the expected type and shape accordingly.

Use RMM's `DeviceBuffer` for Python allocations

---

ci/release/update-version.sh

Adds docs to `update-version.sh` script

[REVIEW] Fix update-version.sh [skip-ci]

---

notebooks/README.md

Add notebooks folder for future notebooks and README referencing notebooks repo.

[REVIEW] Add notebooks folder and README [skip-ci]

---

ci/release/update-version.sh
notebooks/README.md

Auto-merge triggered by push to `branch-0.13` that creates a PR to keep `branch-0.14` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.13 to branch-0.14 [skip ci]

---

CHANGELOG.md

[REVIEW] Fix automerge 0.13 --> 0.14 [skip ci]

---

CHANGELOG.md
python/cuspatial/cuspatial/_lib/interpolate.pxd
python/cuspatial/cuspatial/_lib/interpolate.pyx
python/cuspatial/cuspatial/_lib/shapefile_reader.pxd
python/cuspatial/cuspatial/_lib/shapefile_reader.pyx
python/cuspatial/cuspatial/_lib/soa_readers.pxd
python/cuspatial/cuspatial/_lib/soa_readers.pyx
python/cuspatial/cuspatial/_lib/spatial.pxd
python/cuspatial/cuspatial/_lib/spatial.pyx
python/cuspatial/cuspatial/_lib/trajectory.pxd
python/cuspatial/cuspatial/_lib/trajectory.pyx

This PR fixes `cudf` Cython imports/cimports following https://github.com/rapidsai/cudf/pull/4627. This PR should be merged afterr https://github.com/rapidsai/cudf/pull/4627 is merged.

[REVIEW] Fix cudf legacy Cython imports/cimports

---

CHANGELOG.md
conda/recipes/cuspatial/meta.yaml
conda/recipes/libcuspatial/meta.yaml

Copy of: https://github.com/rapidsai/cuspatial/pull/232/files
Targetted wrong branch.

[REVIEW] Fix libcuspatial dependency

---

CHANGELOG.md
cpp/CMakeLists.txt
cpp/benchmarks/CMakeLists.txt
cpp/tests/CMakeLists.txt
python/cuspatial/setup.cfg

NVStrings and NVCategory have been deleted in cudf.

[REVIEW] Remove nvstrings references from CMakeLists.txt

---

CHANGELOG.md
cpp/src/trajectory/trajectory_distances_and_speeds.cu
cpp/tests/spatial/coordinate_transform_test.cu
cpp/tests/spatial/haversine_test.cpp
cpp/tests/spatial/point_in_polygon_test.cpp
cpp/tests/spatial_window/spatial_window_test.cpp
cpp/tests/trajectory/test_trajectory_bounding_boxes.cu
cpp/tests/trajectory/test_trajectory_distances_and_speeds.cu
cpp/tests/trajectory/trajectory_utilities.cuh

Fixes cudf timestamp construction in response to https://github.com/rapidsai/cudf/pull/5735. ~Blocked by https://github.com/rapidsai/cudf/pull/6053.~

[REVIEW] Fix cudf timestamp construction

---

CHANGELOG.md
cpp/cmake/thirdparty/CMakeLists.txt
cpp/cmake/thirdparty/thrust-ret-if-fail.patch

Copied from https://github.com/rapidsai/cudf/pull/6098

[REVIEW] Patch Thrust to workaround CUDA_CUB_RET_IF_FAIL macro clearing CUDA errors

---

CHANGELOG.md
cpp/src/indexing/construction/detail/phase_2.cuh

bug fix based on [discussions](https://github.com/rapidsai/cuspatial/issues/318)

[WIP] Zero initialize device_uvector before scatter

---

CHANGELOG.md

This PR fixes the merge conflicts in #348.
Just a reminder that this PR should **not** be squash merged. Use a merge commit instead.

Fix merge conflicts in #348

---

cpp/tests/trajectory/trajectory_utilities.cuh

Update location of `make_counting_transform_iterator` after https://github.com/rapidsai/cudf/pull/7306.

Update make_counting_transform_iterator namespace in tests

---

build.sh
ci/cpu/build.sh
conda/recipes/libcuspatial/meta.yaml

- Build using `cmake --build`
- Pass ccache variables to conda recipe
- Use Ninja in CI

ENH Build with `cmake --build` & Pass ccache variables to conda recipe & use Ninja in CI

---

conda/recipes/cuspatial/meta.yaml

Reverts rapidsai/cuspatial#370

Revert "Update conda recipes pinning of repo dependencies" [skip-ci]

---

cpp/cmake/Modules/ConfigureCUDA.cmake

Forward-merge triggered by push to `branch-0.19` that creates a PR to keep `branch-0.20` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-0.19 to branch-0.20 [skip ci]

---

conda/environments/cuspatial_dev_cuda11.0.yml
conda/environments/cuspatial_dev_cuda11.1.yml
conda/environments/cuspatial_dev_cuda11.2.yml

Remove conda defaults channel in dev environments

ENH Remove conda defaults channel in dev environments

---

cpp/src/indexing/construction/detail/phase_1.cuh
cpp/src/indexing/construction/detail/phase_2.cuh
cpp/src/join/detail/intersection.cuh
cpp/src/join/detail/traversal.cuh
cpp/src/join/quadtree_poly_filtering.cu
cpp/src/spatial/haversine.cu
cpp/src/spatial/polygon_bounding_box.cu
cpp/src/spatial/polyline_bounding_box.cu
cpp/src/trajectory/derive_trajectories.cu
cpp/tests/join/point_in_polygon_test_large.cpp

Remove references to deprecated "rmm/thrust_rmm_allocator.h"

---

ci/cpu/upload.sh

Remove progress output on conda packages upload

Remove progress output on conda packages upload

---

conda/recipes/cuspatial/meta.yaml

Pass compiler environment variables to conda python build

Pass compiler environment variables to conda python build

---

cpp/CMakeLists.txt

Bumps the version of cuSpatial in CMakeLists.txt.

Update version to 21.08.00 in cmakelists

---

python/cuspatial/cuspatial/tests/test_from_geopandas.py
python/cuspatial/cuspatial/tests/test_geoarrowbuffers.py
python/cuspatial/cuspatial/tests/test_geodataframe.py
python/cuspatial/cuspatial/tests/test_geoseries.py
python/cuspatial/cuspatial/tests/test_hausdorff_distance.py
python/cuspatial/cuspatial/tests/test_indexing.py
python/cuspatial/cuspatial/tests/test_lonlat_to_cartesian.py
python/cuspatial/cuspatial/tests/test_pip.py
python/cuspatial/cuspatial/tests/test_points_in_spatial_window.py
python/cuspatial/cuspatial/tests/test_polygon_bounding_boxes.py
python/cuspatial/cuspatial/tests/test_polyline_bounding_boxes.py
python/cuspatial/cuspatial/tests/test_shapefile_reader.py
python/cuspatial/cuspatial/tests/test_spatial_join.py
python/cuspatial/cuspatial/tests/test_spline_fit.py
python/cuspatial/cuspatial/tests/test_trajectory.py

Forward-merge triggered by push to `branch-21.08` that creates a PR to keep `branch-21.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.08 to branch-21.10 [skip ci]

---

python/cuspatial/cuspatial/core/gis.py

Stop using now removed _apply_support_method function.

---

python/cuspatial/cuspatial/_lib/interpolate.pyx
python/cuspatial/cuspatial/_lib/spatial_join.pyx
python/cuspatial/cuspatial/utils/column_utils.py

This makes cuspatial compatible with the changes in rapidsai/cudf#9199.

Update Cython Table APIs to match changes in cudf.

---

conda/recipes/cuspatial/meta.yaml

Skip imports tests on arm64

---

ci/cpu/prebuild.sh
conda/recipes/cuspatial/meta.yaml
python/cuspatial/cuspatial/_lib/interpolate.pyx
python/cuspatial/cuspatial/_lib/spatial_join.pyx
python/cuspatial/cuspatial/utils/column_utils.py

Forward-merge triggered by push to `branch-21.10` that creates a PR to keep `branch-21.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.10 to branch-21.12 [skip gpuci]

---

python/cuspatial/cuspatial/_lib/cpp/interpolate.pxd
python/cuspatial/cuspatial/_lib/cpp/spatial_join.pxd
python/cuspatial/cuspatial/_lib/cpp/spatial_window.pxd
python/cuspatial/cuspatial/_lib/interpolate.pyx
python/cuspatial/cuspatial/_lib/spatial_join.pyx
python/cuspatial/cuspatial/_lib/spatial_window.pyx

This PR updates cuspatial to match the changes in rapidsai/cudf#9315.

Remove use of now removed cudf Table object.

---

cpp/cmake/Modules/ConfigureCUDA.cmake
cpp/src/interpolate/cubic_spline.cu
cpp/src/join/quadtree_poly_filtering.cu
cpp/src/spatial/haversine.cu
cpp/src/trajectory/trajectory_bounding_boxes.cu
cpp/src/trajectory/trajectory_distances_and_speeds.cu
python/cuspatial/setup.py

Forward-merge triggered by push to `branch-21.12` that creates a PR to keep `branch-22.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.12 to branch-22.02 [skip gpuci]

---

python/cuspatial/cuspatial/tests/test_pip.py

Following breaking change in `cuDF` [here](https://github.com/rapidsai/cudf/pull/9803), this test needs to be updated

Fix `test_pip_bitmap_column_to_binary_array` test

---

conda/recipes/cuspatial/meta.yaml

Fix imports tests syntax

---

python/cuspatial/cuspatial/tests/test_haversine_distance.py

Fix for breaking changes in rapidsai/cudf#10124.

Swap NumericalColumn.values_host for now removed to_array

---

cpp/include/cuspatial/point_in_polygon.hpp
python/cuspatial/cuspatial/core/gis.py

Forward-merge triggered by push to `branch-22.04` that creates a PR to keep `branch-22.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.04 to branch-22.06 [skip gpuci]

---

.gitignore
build.sh
ci/gpu/build.sh
ci/release/update-version.sh
conda/environments/cuspatial_dev_cuda11.0.yml
conda/environments/cuspatial_dev_cuda11.1.yml
conda/environments/cuspatial_dev_cuda11.2.yml
conda/recipes/cuspatial/build.sh
conda/recipes/cuspatial/meta.yaml
conda/recipes/libcuspatial/meta.yaml
python/cuspatial/CMakeLists.txt
python/cuspatial/cuspatial/_lib/CMakeLists.txt
python/cuspatial/pyproject.toml
python/cuspatial/setup.py

Forward-merge triggered by push to `branch-22.06` that creates a PR to keep `branch-22.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.06 to branch-22.08 [skip gpuci]

---

conda/recipes/cuspatial/conda_build_config.yaml
conda/recipes/cuspatial/meta.yaml
conda/recipes/libcuspatial/meta.yaml

- Simplify recipes using `{{ target_platform }}` for `sysroot` package
- Add `nvcc` to `cuspatial` conda recipe

Fix conda recipes

---

ci/docs/build.sh

This PR updates our docs scripts to build `libcuspatial` docs.

Update docs script to build `libcuspatial` [skip ci]

---

.pre-commit-config.yaml

Updating isort to align with changes in cudf.

Update isort to version 5.10.1

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/pairwise_linestring_distance.cu
cpp/benchmarks/spatial_window.cu
cpp/benchmarks/utility/random.cuh
cpp/include/cuspatial/spatial_window.hpp

Forward-merge triggered by push to `branch-22.08` that creates a PR to keep `branch-22.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.08 to branch-22.10 [skip gpuci]

---

python/cuspatial/cuspatial/core/geoseries.py
python/cuspatial/cuspatial/tests/test_geodataframe.py
python/cuspatial/cuspatial/tests/test_geoseries.py

Forward-merge triggered by push to `branch-22.10` that creates a PR to keep `branch-22.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.10 to branch-22.12 [skip gpuci]

---

.github/workflows/add_issue_to_project.yml

The new project boards should have every issue/PR within them. This workflow makes the addition of the issues/PRs automatic rather than the current manual process.

[REVIEW] Auto-add new Issues and PRs to cuspatial's project

---

ci/checks/style.sh
pyproject.toml

Fix style checks.

---

.pre-commit-config.yaml
ci/checks/style.sh
java/src/main/native/src/cuSpatialJni.cpp
python/cuspatial/cuspatial/__init__.py
python/cuspatial/cuspatial/_lib/distance.pyx
python/cuspatial/cuspatial/_lib/linestring_bounding_boxes.pyx
python/cuspatial/cuspatial/_lib/nearest_points.pyx
python/cuspatial/cuspatial/_lib/polygon_bounding_boxes.pyx
python/cuspatial/cuspatial/_lib/shapefile_reader.pyx
python/cuspatial/cuspatial/_lib/spatial.pyx
python/cuspatial/cuspatial/_lib/spatial_join.pyx
python/cuspatial/cuspatial/_lib/spatial_window.pyx
python/cuspatial/cuspatial/core/spatial/__init__.py
python/cuspatial/setup.py
setup.cfg

Forward-merge triggered by push to `branch-22.12` that creates a PR to keep `branch-23.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.12 to branch-23.02 [skip gpuci]

---

cpp/tests/indexing/point_quadtree_test.cu
cpp/tests/interpolate/cubic_spline_test.cpp
cpp/tests/join/point_in_polygon_test_large.cpp
cpp/tests/join/point_in_polygon_test_small.cpp
cpp/tests/join/point_to_nearest_linestring_test_small.cpp
cpp/tests/join/quadtree_linestring_filtering_test.cu
cpp/tests/join/quadtree_polygon_filtering_test.cu
cpp/tests/spatial/haversine_test.cpp
cpp/tests/spatial/linestring_bbox_test.cu
cpp/tests/spatial/pairwise_point_in_polygon_test.cpp
cpp/tests/spatial/point_in_polygon_test.cpp
cpp/tests/spatial/polygon_bbox_test.cu

Following https://github.com/rapidsai/cudf/pull/12242, this PR updates libcuspatial tests with cudf test macros.

Use Libcudf Test Macro

---

cpp/include/cuspatial_test/vector_equality.hpp
cpp/tests/experimental/indexing/point_quadtree_test.cu
cpp/tests/experimental/spatial/hausdorff_test.cu
cpp/tests/experimental/spatial/haversine_test.cu
cpp/tests/experimental/spatial/linestring_bounding_boxes_test.cu
cpp/tests/experimental/spatial/linestring_intersection_intermediates_remove_if_test.cu
cpp/tests/experimental/spatial/linestring_intersection_with_duplicates_test.cu
cpp/tests/experimental/spatial/point_bounding_boxes_test.cu
cpp/tests/experimental/spatial/point_distance_test.cu
cpp/tests/experimental/spatial/point_linestring_distance_test.cu
cpp/tests/experimental/spatial/point_linestring_nearest_points_test.cu
cpp/tests/experimental/spatial/points_in_range_test.cu
cpp/tests/experimental/spatial/polygon_bounding_boxes_test.cu
cpp/tests/experimental/spatial/sinusoidal_projection_test.cu
cpp/tests/experimental/trajectory/derive_trajectories_test.cu
cpp/tests/experimental/trajectory/trajectory_distances_and_speeds_test.cu

Forward-merge triggered by push to `branch-23.02` that creates a PR to keep `branch-23.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.02 to branch-23.04

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/recipes/cuspatial/conda_build_config.yaml
conda/recipes/libcuspatial/conda_build_config.yaml
cpp/include/cuspatial/distance/linestring_distance.hpp
cpp/include/cuspatial/distance/point_distance.hpp
cpp/include/cuspatial/distance/point_linestring_distance.hpp
cpp/tests/spatial/linestring_intersection_test.cpp
cpp/tests/spatial/point_distance_test.cpp
cpp/tests/spatial/point_linestring_distance_test.cpp
dependencies.yaml

This PR updates builds to use GCC 11.

Update to GCC 11

---

cpp/include/cuspatial/experimental/detail/functors.cuh
cpp/include/cuspatial/experimental/detail/ranges/multilinestring_range.cuh
cpp/include/cuspatial/experimental/detail/ranges/multipolygon_range.cuh
cpp/include/cuspatial/experimental/ranges/multilinestring_range.cuh
cpp/include/cuspatial/experimental/ranges/multipolygon_range.cuh
cpp/include/cuspatial_test/base_fixture.hpp
cpp/tests/CMakeLists.txt
cpp/tests/experimental/range/multilinestring_range_test.cu
cpp/tests/experimental/range/multipolygon_range_test.cu

Forward-merge triggered by push to `branch-23.04` that creates a PR to keep `branch-23.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.04 to branch-23.06

---

build.sh

Addressing upstream rapids-cmake change: https://github.com/rapidsai/rapids-cmake/pull/397

Update `CMAKE_CUDA_ARCHITECTURE` to use new value

---

cpp/src/indexing/point_quadtree.cu
cpp/src/intersection/linestring_intersection.cu
cpp/src/join/quadtree_bbox_filtering.cu
cpp/src/join/quadtree_point_in_polygon.cu
cpp/src/join/quadtree_point_to_nearest_linestring.cu
cpp/src/trajectory/derive_trajectories.cu
cpp/tests/trajectory/test_derive_trajectories.cpp
cpp/tests/trajectory/test_trajectory_bounding_boxes.cu
cpp/tests/trajectory/test_trajectory_distances_and_speeds.cu
docs/source/user_guide/cuspatial_api_examples.ipynb

Forward-merge triggered by push to `branch-23.06` that creates a PR to keep `branch-23.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.06 to branch-23.08

---

ci/release/update-version.sh
cpp/doxygen/Doxyfile

Adding #1187 to `main` for the `23.06` release

[RELEASE] v23.06

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/recipes/cuspatial/conda_build_config.yaml
conda/recipes/cuspatial/meta.yaml
conda/recipes/libcuspatial/conda_build_config.yaml
cpp/CMakeLists.txt
dependencies.yaml
docs/source/developer_guide/build.md
java/src/main/native/CMakeLists.txt
python/cuspatial/CMakeLists.txt
python/cuspatial/pyproject.toml

Updates minimum required CMake version to 3.26.4

Update to CMake 3.26.4

---

cpp/include/cuspatial/detail/algorithm/is_point_in_polygon.cuh
cpp/include/cuspatial/detail/find/find_and_combine_segment.cuh
cpp/include/cuspatial/detail/utility/linestring.cuh
cpp/include/cuspatial/geometry/segment.cuh
cpp/tests/find/find_and_combine_segments_test.cu
cpp/tests/intersection/linestring_intersection_large_test.cu
python/cuspatial/cuspatial/tests/binpreds/test_contains_properly.py

Forward-merge triggered by push to `branch-23.08` that creates a PR to keep `branch-23.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.08 to branch-23.10

---

ci/release/update-version.sh

Fixes copy/paste errors in https://github.com/rapidsai/cuspatial/pull/1263.

fix update-version.sh

---

python/cuspatial/benchmarks/api/bench_api.py
python/cuspatial/benchmarks/conftest.py

Forward-merge triggered by push to `branch-23.10` that creates a PR to keep `branch-23.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.10 to branch-23.12

---

python/cuspatial/cuspatial/core/spatial/distance.py

Forward-merge triggered by push to `branch-23.12` that creates a PR to keep `branch-24.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.12 to branch-24.02

---

python/cuspatial/cuspatial/core/spatial/distance.py

Forward-merge triggered by push to `branch-24.02` that creates a PR to keep `branch-24.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-24.02 to branch-24.04

---

python/cuspatial/cuspatial/core/_column/geocolumn.py
python/cuspatial/cuspatial/core/binops/intersection.py

This API is planned for removal in cudf: https://github.com/rapidsai/cudf/pull/14786

Use ListColumn instead of build_list_column

---

ci/build_wheel_cuspatial.sh

This fixes an error introduced in #1304.

Make sure cudf uses pyarrow's libarrow during wheel builds 

---

python/cuproj/pyproject.toml
python/cuspatial/pyproject.toml

Exclude tests from builds

---

.devcontainer/cuda12.8-conda/devcontainer.json
.devcontainer/cuda12.8-pip/devcontainer.json
.github/workflows/pr.yaml
conda/environments/all_cuda-128_arch-x86_64.yaml
dependencies.yaml

Manual forward merge from 25.02 to 25.04. This PR should not be squashed.

Forward-merge branch-25.02 to branch-25.04

---

.github/workflows/pr.yaml

Fixes undesired CI skips in #1523.

Use test_python changed files list for Python tests.

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-128_arch-x86_64.yaml
conda/recipes/cuproj/conda_build_config.yaml
conda/recipes/cuspatial/conda_build_config.yaml
conda/recipes/libcuspatial/conda_build_config.yaml
cpp/CMakeLists.txt
cpp/cuproj/CMakeLists.txt
dependencies.yaml
java/src/main/native/CMakeLists.txt
python/cuproj/CMakeLists.txt
python/cuproj/cuproj/cuprojshim/CMakeLists.txt
python/cuproj/pyproject.toml
python/cuspatial/CMakeLists.txt
python/cuspatial/pyproject.toml
python/libcuspatial/CMakeLists.txt
python/libcuspatial/pyproject.toml

Update CMake minimum required to 3.30.4 across all of RAPIDS

Require CMake 3.30.4
