rapidsai/cuspatial

- .github/CODEOWNERS
- CHANGELOG.md
Adds a GitHub CODEOWNERS file. 
@dillon-cullinan please create the following initial groups in the rapidsai Org (can expand as needed)
`@rapidsai/cuspatial-cpp-codeowners`: @harrism @jrhemstad 
`@rapidsai/cuspatial-python-codeowners`: @thomcom @kkraus14 
`@rapidsai/cuspatial-cmake-codeowners`: @harrism @thomcom @kkraus14 
`@rapidsai/cuspatial-java-codeowners`: @revans2 @jlowe 
`@rapidsai/cuspatial-ops-codeowners`: Same as `@rapidsai/cudf-ops-codeowners` or what you think is appropriate.
> Add CODEOWNERS

- CHANGELOG.md
- python/cuspatial/demos/hausdorff_clustering_test_toy.py
- python/cuspatial/demos/hausdorff_distance_verify_locust256.py
- python/cuspatial/demos/haversine_distance_test_nyctaxi.py
- python/cuspatial/demos/pip_verify_shapely_locust.py
- python/cuspatial/demos/stq_test_soa_locust.py
- python/cuspatial/demos/traj_demo_derive_subset_locus.py
- python/cuspatial/demos/traj_test_soa_locust.py
All the demos are updated with the proper API for python usage.
There's a substantial bug in `traj_test_soa_locust.py` because of the timestamps and their custom format being sent in as integers to `cudf::timestamp`. I believe this produces many nonsensical trajectory durations, and puts a lot of bad data into the final output dataframe. I'll have to write a good way to get `its_timestamps` into `cudf::timestamps`. It won't happen this afternoon.
> Update all demos with python API.

- CHANGELOG.md
- python/cuspatial/cuspatial/core/gis.py
We learned lat/lon in school, that's silly. Lon is change in the x coordinate, lat in change in the y coordinate. Fix the ordering for haversine.
> Ordering should be lon/lat to reflect x/y

- CHANGELOG.md
- cpp/tests/trajectory/test_trajectory_derive.cu
Missing <random> header fixing compilation error for tests
One of the tests had a missing header causing compilation issue in cpp tests
> [BUGFIX] added missing header in tests

- CHANGELOG.md
- python/cuspatial/cuspatial/core/gis.py
- python/cuspatial/cuspatial/tests/test_pip.py
- python/cuspatial/cuspatial/utils/gis_utils.py
Summary of Changes
- Requires and makes explicit the need for a width parameter in the bitmap to binary conversion utility. This is necessary for downstream usage in `point_in_polygon_bitmap`, ensuring that the dataframe will have the same number of columns as the number of polygon IDs.
- Updates tests accordingly
> [REVIEW] Require width parameterization of bitmap to binary conversion

- CHANGELOG.md
- ci/release/update-version.sh
Added `update-version.sh`, consistent with other RAPIDS repos, to allow CI to update to the next version.
Tested by running with the `major` arg and observing the major version increment in `cpp/CMakeLists.txt`
> Added update-version.sh

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/src/io/soa/point_soa_reader.cu
- cpp/src/io/soa/polygon_soa_reader.cu
- cpp/src/io/soa/timestamp_soa_reader.cu
- cpp/src/io/soa/uint32_soa_reader.cu
- cpp/src/trajectory/subset_trajectories.cu
- cpp/src/utility/utility.hpp
- cpp/tests/query/spatial_window_test_toy.cu
- cpp/tests/spatial/coordinate_transform_toy.cu
- cpp/tests/spatial/hausdorff_compare.cu
- cpp/tests/spatial/hausdorff_test.cu
- cpp/tests/spatial/hausdorff_toy.cu
- cpp/tests/spatial/haversine_toy.cu
- cpp/tests/spatial/pip_compare.cu
- cpp/tests/spatial/pip_test.cu
- cpp/tests/spatial/pip_toy.cu
- cpp/tests/trajectory/test_trajectory_derive.cu
- cpp/tests/trajectory/test_trajectory_distance_speed.cu
- cpp/tests/trajectory/test_trajectory_subset.cu
- cpp/tests/trajectory/trajectory_spatial_bounds_toy.cu
- python/cuspatial/cuspatial/_lib/trajectory.pxd
- python/cuspatial/cuspatial/tests/test_haversine_distance.py
Modify headers with various `legacy` paths.
> [REVIEW] Fix legacy migrations so cuspatial builds again

- CHANGELOG.md
- ci/cpu/upload_anaconda.sh
We no longer rely on these labels for version matching and use `cudatoolkit` package to do so.
> FIX Remove unused CUDA conda labels

- .github/CODEOWNERS
- CHANGELOG.md
No java component in cuspatial, so removing that as well.
> [REVIEW] Update OPS codeowners group name

- CHANGELOG.md
- cpp/src/io/shp/polygon_shapefile_reader.cu
- cpp/src/io/soa/point_soa_reader.cu
- cpp/src/io/soa/polygon_soa_reader.cu
- cpp/src/io/soa/timestamp_soa_reader.cu
- cpp/src/io/soa/uint32_soa_reader.cu
- cpp/src/utility/utility.hpp
libcuspatial is no longer building after recent changed to libcudf, specifically moving `utilities/error_utils.hpp` to `cudf/utilities/error.hpp`.
After these changes, I'm still failing to build with missing `cub/util_type.cuh`, but that could be an issue with my build environment.
> [WIP] Fixing error_utils.hpp

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/src/io/shp/polygon_shapefile_reader.cu
- cpp/src/io/soa/polygon_soa_reader.cu
- cpp/src/query/spatial_window_points.cu
- cpp/src/spatial/hausdorff.cu
- cpp/src/trajectory/derive_trajectories.cu
- cpp/src/trajectory/subset_trajectories.cu
- python/cuspatial/cuspatial/tests/test_hausdorff_distance.py
Added flag to not treat deprecation warnings as errors, for now. This will likely be removed when the RMM API calls have been updated for 0.14.
> [BUG] Added flag to not treat deprecation warnings as errors, for now.

- CHANGELOG.md
- cpp/src/io/shp/polygon_shapefile_reader.cu
- cpp/src/io/soa/polygon_soa_reader.cu
- cpp/src/query/spatial_window_points.cu
- cpp/src/spatial/hausdorff.cu
- cpp/src/trajectory/derive_trajectories.cu
- cpp/src/trajectory/subset_trajectories.cu
(1) fix invalid pointer bug in `auto exec_policy=rmm::exec_policy(stream)->on(stream)` by declaring `rmm::exec_policy(stream)` first and then using the variable with `->on(stream)`. 
(2) fix wrong vertex positions in polygon_soa_reader and shapefile_soa_reader. The bug affects multi-polygons with multiple rings only.
> [REVIEW] fix dangling exec_policy pointer and invalid num_ring argument

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/src/io/shp/polygon_shapefile_reader.cpp
- cpp/src/io/shp/polygon_shapefile_reader.cu
NVCC 10.2 + GCC 7.x doesn't seem to like some of the code included with GDAL headers. This PR moves usage of GDAL into a .cpp file to work around  the  following compiler errors previously seen: 
```
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1761): error: identifier "__builtin_ia32_sqrtsd_round" is undefined
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(1770): error: identifier "__builtin_ia32_sqrtss_round" is undefined
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2728): error: identifier "__builtin_ia32_scalefsd_round" is undefined
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(2737): error: identifier "__builtin_ia32_scalefss_round" is undefined
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h(11265): error: identifier …
```
> [REVIEW] Fix compilation error by moving GDAL functionality to  .cpp

- CHANGELOG.md
- python/cuspatial/cuspatial/tests/test_haversine_distance.py
Cudf changed series indexing rules to require `.iloc` for writing. This PR adds that to haversine tests, which are breaking other PRs.
> [REVIEW] Fix broken haversine tests caused by cudf migration

- CHANGELOG.md
- cpp/tests/interpolate/cubic_spline_test.cpp
- python/cuspatial/cuspatial/tests/test_haversine_distance.py
Something in the RMM API changed such that `rmmIntialize(nullptr)` needs to be called before `RMM_TRY`. This is now handled in `cubic_spline_test.cpp`.
> [REVIEW] Remove use of RMM libraries and use cudf test utils correctly.

- CHANGELOG.md
- cpp/benchmarks/CMakeLists.txt
Fixes benchmark build by removing `test_benchmark.cpp` from cmakelists, as it was removed in #215.
> [REVIEW] remove test_benchmark.cpp from cmakelists

- CHANGELOG.md
- cpp/src/indexing/construction/detail/phase_1.cuh
- cpp/src/indexing/construction/detail/phase_2.cuh
- cpp/src/indexing/construction/detail/utilities.cuh
- cpp/src/indexing/construction/point_quadtree.cu
- cpp/tests/indexing/point_quadtree_test.cu
- python/cuspatial/cuspatial/_lib/quadtree.pyx
- python/cuspatial/cuspatial/core/indexing.py
- python/cuspatial/cuspatial/tests/test_indexing.py
This PR fixes a potential thrust launch failure in the case there are no valid non-leaf quadrants. This is easy to trigger if the user-provided `scale` value doesn't lead to computing any common Morton code keys, and all points are grouped into separate top-level leaf quadrants.
> [REVIEW] Fix potential thrust launch failure in quadtree building

- CHANGELOG.md
- cpp/include/cuspatial/trajectory.hpp
- cpp/src/spatial/point_in_polygon.cu
- cpp/tests/spatial/point_in_polygon_test.cpp
- docs/source/api.rst
- python/cuspatial/cuspatial/core/gis.py
- python/cuspatial/cuspatial/core/indexing.py
- python/cuspatial/cuspatial/core/interpolate.py
- python/cuspatial/cuspatial/core/spatial_window.py
- python/cuspatial/cuspatial/core/trajectory.py
- python/cuspatial/cuspatial/io/shapefile.py
- python/cuspatial/cuspatial/tests/test_pip.py
This PR fixes a few formatting issues in our Python docs and adds all the new methods to the Sphinx `api.rst` manifest.
If you're using `rapids-compose`, here's an easy way to build the python docs:
```shell
make html -C $CUSPATIAL_HOME/docs
```
Or if you're doing a lot of docs editing and want to auto-rebuild the docs on save, you can do this:
```shell
echo "rapids" | sudo -S apt update && echo "rapids" | sudo -S apt install entr
find $CUSPATIAL_HOME/python $CUSPATIAL_HOME/docs/source \
| entr sh -c "make html -C $CUSPATIAL_HOME/docs"
```
<details><summary>Expand this to see a screenshot of the rendered docs</summary>
</details>
> [REVIEW] Add python methods to api.rst, fix formatting

- CHANGELOG.md
- cpp/include/cuspatial/polygon_bounding_box.hpp
- cpp/include/cuspatial/polyline_bounding_box.hpp
- cpp/include/cuspatial/trajectory.hpp
- cpp/src/spatial/polyline_bounding_box.cu
- cpp/tests/spatial/polyline_bbox_test.cu
- docs/source/api.rst
- python/cuspatial/cuspatial/_lib/polygon_bounding_boxes.pyx
- python/cuspatial/cuspatial/_lib/polyline_bounding_boxes.pyx
- python/cuspatial/cuspatial/_lib/trajectory.pyx
- python/cuspatial/cuspatial/core/gis.py
- python/cuspatial/cuspatial/core/trajectory.py
- python/cuspatial/cuspatial/tests/test_polygon_bounding_boxes.py
- python/cuspatial/cuspatial/tests/test_polyline_bounding_boxes.py
- python/cuspatial/cuspatial/tests/test_trajectory.py
Follow-up PR to https://github.com/rapidsai/cuspatial/pull/145
* Renames the `polyline_bounding_boxes` function's `R` parameter to `expansion_radius`
* Updates to the `polygon_bounding_boxes` and `polyline_bounding_boxes` C++ and Python docstrings
> [REVIEW] Fix polygon and polyline docstrings

- CHANGELOG.md
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/meta.yaml
Fixes libcuspatial dependency to be the same git hash. Also removes its runtime dependency as that should be compiled. You can see in the screenshot how the dependency doubles up and can cause conda solver issues.
> [REVIEW] Fix libcuspatial dependency

- CHANGELOG.md
- cpp/benchmarks/fixture/benchmark_fixture.hpp
https://github.com/rapidsai/rmm/pull/396 removed all deprecated headers and APIs. 
This PR cleans up references to unused, deprecated RMM headers.
> Remove references to deprecated rmm headers.

- CHANGELOG.md
- ci/gpu/build.sh
Install dependencies via `rapids-build-env` (which is pre-installed in the containers).
This brings the repo in line with https://docs.rapids.ai/maintainers/depmgmt/
> Install dependencies via meta package

- CHANGELOG.md
- ci/cpu/build.sh
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/meta.yaml
Removing unnecessary git clone from build script as well. cuDF should not need to be cloned in the CPU build script since the conda build should download the correct version.
> [REVIEW] Add short commit to conda package

- CHANGELOG.md
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/meta.yaml
Need to restrict the gdal version more closely since 3.0.2 and 3.1.0 are linked in an incompatible way. Since 3.1.0 works, just restrict to that minor version.
> Pin gdal version

- CHANGELOG.md
- cpp/benchmarks/fixture/benchmark_fixture.hpp
Replace calls to rmmInit/Finalize with cnmem_memory_resource.
> [REVIEW] Fix benchmark_fixture to use RMM resources

- CHANGELOG.md
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/meta.yaml
`cuxfilter` has a dependency on `geopandas` which seems to be locked to `gdal` 3.0.x.
> [REVIEW] Pin gdal to be compatible with cuxfilter

- CHANGELOG.md
- cpp/include/cuspatial/point_quadtree.hpp
- cpp/src/indexing/construction/detail/phase_1.cuh
- cpp/src/indexing/construction/detail/phase_2.cuh
- cpp/src/indexing/construction/point_quadtree.cu
- cpp/tests/indexing/point_quadtree_test.cu
- python/cuspatial/cuspatial/tests/test_indexing.py
This PR replaces uses of `rmm::device_vector` with `rmm::device_uvector`, and changes `cudf::INT8` and `cudf::INT32` to the new unsigned integer types.
I see a runtime improvement on the NYC taxi notebook from ~77 ms to 65.5 ms with FP32 points.
> [REVIEW] Use rmm::device_uvector and cudf::UINT types for quadtree construction

- .pre-commit-config.yaml
- CHANGELOG.md
- ci/checks/style.sh
- conda/environments/cuspatial_dev_cuda10.0.yml
- conda/environments/cuspatial_dev_cuda10.1.yml
- conda/environments/cuspatial_dev_cuda10.2.yml
- conda/environments/cuspatial_dev_cuda9.2.yml
- python/cuspatial/setup.py
* Pin flake8, black, isort versions
* Update `ci/checks/style.sh` for new isort version
Similar to changes made in https://github.com/rapidsai/cudf/pull/5643
> [REVIEW] Fix CI style check failures

- CHANGELOG.md
- ci/local/build.sh
PR fixes local docker image `(DOCKER_IMAGE` string) used by build script:
- Programmatically inserts minor version num
- Replaces py3.6 with py3.7 (in line with dropping Python 3.6 support for v0.15 -> https://github.com/rapidsai/ops/issues/1017)
> [WIP] update docker image [skip-ci]

- CHANGELOG.md
Should fix auto-merge pr #236, according to https://docs.rapids.ai/maintainers/gpuci/.
> merge 0.14 to 0.15

- CHANGELOG.md
- cpp/tests/spatial/coordinate_transform_test.cu
- cpp/tests/spatial/haversine_test.cpp
- cpp/tests/spatial/point_in_polygon_test.cpp
- cpp/tests/spatial_window/spatial_window_test.cpp
Fixes compiler errors from cuDF's new duration types recently added as part of https://github.com/rapidsai/cudf/issues/5272.
> [REVIEW] Fix compiler errors from cudf's new duration types

- CHANGELOG.md
- cpp/benchmarks/fixture/benchmark_fixture.hpp
Replaces usage of `cnmem_memory_resource` in benchmark fixture with `pool_memory_resource`.
Also adds option to test with `binning_memory_resource`.
> [REVIEW] Replace CNMeM with pool_memory_resource

- CHANGELOG.md
- cpp/include/cuspatial/spatial_join.hpp
- cpp/src/join/quadtree_poly_filtering.cu
- cpp/tests/join/point_in_polygon_test_large.cpp
- cpp/tests/join/point_in_polygon_test_small.cpp
- cpp/tests/join/point_to_nearest_polyline_test_small.cpp
- cpp/tests/join/quadtree_polygon_filtering_test.cu
- cpp/tests/join/quadtree_polyline_filtering_test.cu
- docs/source/api.rst
- python/cuspatial/cuspatial/__init__.py
- python/cuspatial/cuspatial/_lib/cpp/spatial_join.pxd
- python/cuspatial/cuspatial/_lib/spatial_join.pyx
- python/cuspatial/cuspatial/core/spatial_join.py
- python/cuspatial/cuspatial/tests/test_spatial_join.py
As mentioned in https://github.com/rapidsai/cuspatial/pull/149#discussion_r467185668, this PR renames the `quad_bbox_join` method to a more descriptive `join_quadtree_and_bounding_boxes`.
> [REVIEW] Rename quad_bbox_join to join_quadtree_and_bounding_boxes

- ci/checks/changelog.sh
- ci/cpu/upload_anaconda.sh
This PR removes unecessary references to master or updates references to the new main branch in CI scripts and other OPS-owned files.
> [REVIEW] Update CI scripts to remove references to master [skip ci] 

- ci/checks/changelog.sh
- ci/cpu/upload_anaconda.sh
Auto-merge triggered by push to `branch-0.15` that creates a PR to keep `branch-0.16` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.15 to branch-0.16 [skip ci]

- CONTRIBUTING.md
- cpp/cmake/Templates/GoogleBenchmark.CMakeLists.txt.cmake
This PR removes unecessary references to master or updates references to the new main branch in CI scripts and other OPS-owned files.
> [REVIEW] Update docs to remove references to master [skip ci]

- CHANGELOG.md
- cpp/cmake/Templates/GoogleBenchmark.CMakeLists.txt.cmake
This PR updates `GoogleBenchmark.CMakeLists.txt.cmake` to match the version used by rmm ([link](https://github.com/rapidsai/rmm/blob/branch-0.16/cmake/Templates/GoogleBenchmark.CMakeLists.txt.cmake)) and cudf ([link](https://github.com/rapidsai/cudf/blob/branch-0.16/cpp/cmake/Templates/GoogleBenchmark.CMakeLists.txt.cmake)). This change was suggested by @harrism as a result of the findings from PR #271.
> [REVIEW] Update googlebenchmark version to match rmm & cudf

- CHANGELOG.md
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/meta.yaml
- cpp/include/cuspatial/coordinate_transform.hpp
- cpp/include/cuspatial/hausdorff.hpp
- cpp/include/cuspatial/haversine.hpp
- cpp/include/cuspatial/point_in_polygon.hpp
- cpp/include/cuspatial/point_quadtree.hpp
- cpp/include/cuspatial/polygon_bounding_box.hpp
- cpp/include/cuspatial/polyline_bounding_box.hpp
- cpp/include/cuspatial/shapefile_reader.hpp
- cpp/include/cuspatial/spatial_join.hpp
- cpp/include/cuspatial/spatial_window.hpp
- cpp/include/cuspatial/trajectory.hpp
- cpp/src/indexing/construction/detail/utilities.cuh
- cpp/src/interpolate/cubic_spline.cu
- cpp/tests/trajectory/trajectory_utilities.cuh
Fixes compile errors using the latest RMM on branch-0.16. Similar to https://github.com/rapidsai/cudf/pull/6121.
> [REVIEW] Replace RMM get_default_resource with get_current_device_resource

- CHANGELOG.md
- cpp/cmake/Modules/ConfigureGoogleBenchmark.cmake
- cpp/cmake/Modules/ConfigureGoogleTest.cmake
- cpp/cmake/Templates/GoogleBenchmark.CMakeLists.txt.cmake
- cpp/cmake/Templates/GoogleTest.CMakeLists.txt.cmake
This PR adds project names to cuDF's external project templates to squash cmake warnings they currently create. This is along the lines of rapidsai/rmm#541
It also changes CMAKE_SOURCE_DIR to CMAKE_CURRENT_SOURCE_DIR in case this library is build from another project using add_subdirectory (admittedly rare, but that was the motivation for rapidsai/rmm#541).
> [REVIEW] Fix CMake warnings in external projects

- CHANGELOG.md
- python/cuspatial/cuspatial/_lib/move.pxd
- python/cuspatial/cuspatial/_lib/spatial_join.pyx
- python/cuspatial/cuspatial/core/spatial_join.py
- python/cuspatial/cuspatial/tests/test_spatial_join.py
* Fixes a cython compilation error from cuDF adding more `move()` overloads
* Fixes mislabeled column names in `quadtree_point_in_polygon`
Closes #284
> [REVIEW] Fix mislabeled columns in Python spatial join result table

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/benchmarks/CMakeLists.txt
- cpp/tests/CMakeLists.txt
Fix for RMM being header only, also removes cmake option `CMAKE_CXX11_ABI` following other RAPIDS repos.
> [REVIEW] Updates for RMM being header only

- CHANGELOG.md
- docs/source/api.rst
Fixes Python docs issue causing the first argument of each public function not to render.
Closes https://github.com/rapidsai/cuspatial/issues/285.
> [REVIEW] Fix issue causing python docs to exclude the first parameter of each cuspatial function

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/benchmarks/CMakeLists.txt
- cpp/src/spatial/polygon_bounding_box.cu
- cpp/tests/CMakeLists.txt
- python/cuspatial/cuspatial/core/gis.py
Due to libcudf splitting into multiple shared libraries to fix debug builds, libcuspatial was left in a broken state. We don't fully understand why, but it seems like some combination of the linker pruning the `libcudf.so` dependency since it finds no symbols it uses in it BEFORE it adds `DT_NEEDED` entries from `libcudf.so` where it does find symbols.
Added some linker flags to temporarily fix the build while we continue investigating a more proper solution from the libcudf side.
Also fixed a minor gcc9 issue related to a copy elision.
Also fixed usage of a removed cudf Python API.
> [REVIEW] Fix build issues related to libcudf/cudf changes

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/benchmarks/CMakeLists.txt
- cpp/tests/CMakeLists.txt
Planning to upgrade to cmake 3.18 in the near future and the CUDA_ARCHITECTURES change is a breaking change, so pinning to 3.17 policies to prevent the breakages.
> [REVIEW] Pin cmake policies to cmake 3.17 version

- CHANGELOG.md
- cpp/benchmarks/synchronization/synchronization.cpp
- cpp/benchmarks/synchronization/synchronization.hpp
- cpp/include/cuspatial/cubic_spline.hpp
- cpp/src/indexing/construction/detail/phase_1.cuh
- cpp/src/indexing/construction/detail/phase_2.cuh
- cpp/src/indexing/construction/detail/utilities.cuh
- cpp/src/indexing/construction/point_quadtree.cu
- cpp/src/interpolate/cubic_spline.cu
- cpp/src/io/shp/polygon_shapefile_reader.cu
- cpp/src/join/detail/intersection.cuh
- cpp/src/join/detail/traversal.cuh
- cpp/src/join/quadtree_point_in_polygon.cu
- cpp/src/join/quadtree_point_to_nearest_polyline.cu
- cpp/src/join/quadtree_poly_filtering.cu
- cpp/src/spatial/hausdorff.cu
- cpp/src/spatial/haversine.cu
- cpp/src/spatial/lonlat_to_cartesian.cu
- cpp/src/spatial/point_in_polygon.cu
- cpp/src/spatial/polygon_bounding_box.cu
- cpp/src/spatial/polyline_bounding_box.cu
- cpp/src/spatial_window/spatial_window.cu
- cpp/src/trajectory/derive_trajectories.cu
- cpp/src/trajectory/trajectory_bounding_boxes.cu
- cpp/src/trajectory/trajectory_distances_and_speeds.cu
- cpp/tests/trajectory/trajectory_utilities.cuh
This PR converts all usage of `cudaStream_t` in cuSpatial to `rmm::cuda_stream_view`, following on from  rapidsai/cudf#6646, rapidsai/cudf#6648 and rapidsai/cudf#6744.
This PR should only depend on the first of those, but it's possible it depends on changes from all of them. CI will tell us...
Also reorders stream parameters to occur before MR parameters in all functions.
> Convert cudaStream_t to rmm::cuda_stream_view

- CHANGELOG.md
- cpp/tests/join/point_in_polygon_test_large.cpp
Update `cudf::gather` callsite in `point_in_polygon_test_large` to account for the new out of bounds policy parameter.
> [REVIEW] Fix point in polygon test for cudf::gather breaking change

- CHANGELOG.md
- cpp/tests/join/point_in_polygon_test_large.cpp
Auto-merge triggered by push to `branch-0.17` that creates a PR to keep `branch-0.18` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.17 to branch-0.18 [skip ci]

- CHANGELOG.md
- cpp/src/indexing/construction/detail/phase_1.cuh
- cpp/src/indexing/construction/detail/phase_2.cuh
- cpp/src/indexing/construction/point_quadtree.cu
- cpp/src/interpolate/cubic_spline.cu
- cpp/src/io/shp/polygon_shapefile_reader.cu
- cpp/src/join/detail/intersection.cuh
- cpp/src/join/detail/traversal.cuh
- cpp/src/join/quadtree_point_in_polygon.cu
- cpp/src/join/quadtree_point_to_nearest_polyline.cu
- cpp/src/join/quadtree_poly_filtering.cu
- cpp/src/spatial/hausdorff.cu
- cpp/src/spatial/haversine.cu
- cpp/src/spatial/lonlat_to_cartesian.cu
- cpp/src/spatial/polygon_bounding_box.cu
- cpp/src/spatial/polyline_bounding_box.cu
- cpp/src/trajectory/derive_trajectories.cu
- cpp/src/trajectory/trajectory_bounding_boxes.cu
- cpp/src/trajectory/trajectory_distances_and_speeds.cu
Updates libcudf to use the new, simplified rmm::exec_policy and include the new refactored headers rmm/exec_policy.hpp and rmm/device_vector.hpp
The new exec_policy can be passed directly to Thrust, no longer any need to call rmm::exec_policy(stream)->on(stream).
Depends on rapidsai/rmm#647
> Use simplified `rmm::exec_policy`

- ci/gpu/build.sh
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/meta.yaml
Bump `gdal` from 3.1.x to 3.2.x. Supersedes #339. This is inline with conda-forge's current migration to gdal=3.2.x (see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/922 and https://conda-forge.org/status/#gdal32).
Update on rapidsai/integration is at https://github.com/rapidsai/integration/pull/211.
> [REVIEW] Pin gdal to 3.2.x

- cpp/src/join/detail/traversal.cuh
- cpp/src/join/quadtree_point_in_polygon.cu
After rapidsai/rmm#725 is merged, this PR updates cuspatial to eliminate passing literal values to `device_uvector::set_element_async`.
> Eliminate literals passed to device_uvector::set_element_async

- conda/recipes/cuspatial/meta.yaml
Ensure all conda packages created in this repo that depend on other packages are all version pinned to the same build number. This way it prevents a conda solve from picking mismatched versions of `cuspatial` and `libcuspatial` that can break this repo during builds and testing.
> Update conda recipes pinning of repo dependencies

- cpp/CMakeLists.txt
Fix issue where conda installed `libcuspatial` can't find other conda-installed libraries like GDAL.
Related issue in cuDF: https://github.com/rapidsai/cudf/pull/7863
> Set `install_rpath` for libcuspatial

- cpp/CMakeLists.txt
- cpp/cmake/Modules/ConfigureCUDA.cmake
Decrease library size by using fatbin compression.
cuDF PR for context: https://github.com/rapidsai/cudf/pull/7583
> [REVIEW] ENH Reduce cuspatial library size

- cpp/src/indexing/construction/detail/phase_1.cuh
- cpp/src/indexing/construction/detail/phase_2.cuh
- cpp/src/indexing/construction/detail/utilities.cuh
- cpp/src/indexing/construction/point_quadtree.cu
- cpp/src/join/detail/intersection.cuh
- cpp/src/join/detail/traversal.cuh
- cpp/src/join/quadtree_point_in_polygon.cu
- cpp/src/join/quadtree_point_to_nearest_polyline.cu
- cpp/src/join/quadtree_poly_filtering.cu
- cpp/tests/join/point_in_polygon_test_large.cpp
[cuDF updated to Thrust v1.12.0 today](https://github.com/rapidsai/cudf/pull/7923), which means we need to update too.
* Fixes GCC 9 RVO compile warning/error
* Removes our `make_zip_iterator` convenience fn because it's now part of Thrust
Thrust 1.11.0 included a new radix sort in CUB, so hopefully we see some nice speedups in our routines as well. Hooray!
> Update to new Thrust 1.12.0 APIs

- cpp/src/indexing/construction/point_quadtree.cu
- cpp/tests/trajectory/trajectory_utilities.cuh
Updates necessary due to https://github.com/rapidsai/rmm/pull/740.
> Update cuspatial to use `rmm::cuda_stream_default` everywhere

- cpp/cmake/thirdparty/CUSPATIAL_GetCPM.cmake
- cpp/cmake/thirdparty/CUSPATIAL_GetCUDF.cmake
Update CPM with a [fix for `FETCHCONTENT_BASE_DIR`](https://github.com/cpm-cmake/CPM.cmake/pull/244).
> Update to CPM with fix for `FETCHCONTENT_BASE_DIR`

- cpp/src/spatial/hausdorff.cu
Fixes this error that curiously only shows up when `CMAKE_BUILD_TYPE=Debug`:
```
cpp/src/spatial/hausdorff.cu:81:18: error: comparison of integer expressions of different signedness: 'const long unsigned int' and 'int' [-Werror=sign-compare]
cc1plus: all warnings being treated as errors
```
> fix -Werror=sign-compare causing debug builds to fail

- ci/cpu/build.sh
Remove `rapidsai-nightly` conda channel when building main branch
> Remove 'rapidsai-nightly' conda channel when building main branch

- python/cuspatial/cuspatial/__init__.py
> Import `_version` in `__init__.py` so that `versioneer` can be used.

- conda/environments/cuspatial_dev_cuda11.0.yml
- conda/environments/cuspatial_dev_cuda11.1.yml
- conda/environments/cuspatial_dev_cuda11.2.yml
- cpp/CMakeLists.txt
- cpp/cmake/thirdparty/CUSPATIAL_GetCUDF.cmake
* Update cuspatial version for calver
* Fix CMake `FindPackage(cudf)`
> Update cuspatial version for calver, fix CMake FindPackage cudf

- cpp/src/io/shp/polygon_shapefile_reader.cu
Simple PR that adds a `std::move` around passing a device_buffer into a column factory. This will be necessary once rapidsai/rmm/#775 is merged.
> Move rmm::device_buffer instead of copying

- conda/recipes/libcuspatial/meta.yaml
This PR updates the environment variable thats used to determine the `cuda_version` varaible in our conda recipes.
The `CUDA` environment variable is explicitly set by the Ops team in our Jenkins jobs, whereas `CUDA_VERSION` comes from the `nvidia/cuda` Docker images that we base our images from.
> Update environment variable used to determine `cuda_version`

- conda/environments/cuspatial_dev_cuda11.0.yml
- conda/environments/cuspatial_dev_cuda11.1.yml
- conda/environments/cuspatial_dev_cuda11.2.yml
- conda/recipes/libcuspatial/meta.yaml
- python/cuspatial/cuspatial/geometry/geocolumn.py
- python/cuspatial/cuspatial/geometry/geodataframe.py
- python/cuspatial/cuspatial/tests/test_from_geopandas.py
- python/cuspatial/cuspatial/tests/test_geoarrowbuffers.py
- python/cuspatial/cuspatial/tests/test_geodataframe.py
- python/cuspatial/cuspatial/tests/test_geoseries.py
- python/cuspatial/cuspatial/tests/test_hausdorff_distance.py
- python/cuspatial/cuspatial/tests/test_indexing.py
- python/cuspatial/cuspatial/tests/test_lonlat_to_cartesian.py
- python/cuspatial/cuspatial/tests/test_pip.py
- python/cuspatial/cuspatial/tests/test_points_in_spatial_window.py
- python/cuspatial/cuspatial/tests/test_polygon_bounding_boxes.py
- python/cuspatial/cuspatial/tests/test_polyline_bounding_boxes.py
- python/cuspatial/cuspatial/tests/test_shapefile_reader.py
- python/cuspatial/cuspatial/tests/test_spatial_join.py
- python/cuspatial/cuspatial/tests/test_spline_fit.py
- python/cuspatial/cuspatial/tests/test_trajectory.py
This PR contains three distinct changes required to get cuspatial builds working and tests passing again:
1. RMM switched to rapids-cmake (rapidsai/rmm#800), which requires CMake 3.20.1, so this PR includes the required updates for that.
2. The Arrow upgrade in cudf also moved the location of testing utilities (rapidsai/cudf#7495). Long term cuspatial needs to move away from use of the testing utilities, which are not part of cudf's public API, but we are currently blocked by rapidsai/cudf#8646, so this PR just imports the internal `assert_eq` method as a stopgap to get tests passing.
3. The changes in rapidsai/cudf#8373 altered the way that metadata was propagated to libcudf outputs from previously existing cuDF Python objects. The new code paths require cuspatial to override metadata …
> Update CMake, fix testing use of assert_eq, and correct metadata copying

- cpp/tests/io/shp/polygon_shapefile_reader_test.cpp
- cpp/tests/join/point_in_polygon_test_large.cpp
- cpp/tests/spatial/coordinate_transform_test.cu
- cpp/tests/spatial/hausdorff_test.cpp
- cpp/tests/spatial/haversine_test.cpp
- cpp/tests/spatial/point_in_polygon_test.cpp
- cpp/tests/spatial_window/spatial_window_test.cpp
rapidsai/cudf#8666 modified `cudf::test` APIs to accept a verbosity enum as a parameter to control output, which is backwards incompatible with the previously boolean parameter.
> Fix usage of assert_columns* APIs.

- python/cuspatial/cuspatial/tests/test_from_geopandas.py
- python/cuspatial/cuspatial/tests/test_geoarrowbuffers.py
- python/cuspatial/cuspatial/tests/test_geodataframe.py
- python/cuspatial/cuspatial/tests/test_geoseries.py
- python/cuspatial/cuspatial/tests/test_hausdorff_distance.py
- python/cuspatial/cuspatial/tests/test_indexing.py
- python/cuspatial/cuspatial/tests/test_lonlat_to_cartesian.py
- python/cuspatial/cuspatial/tests/test_pip.py
- python/cuspatial/cuspatial/tests/test_points_in_spatial_window.py
- python/cuspatial/cuspatial/tests/test_polygon_bounding_boxes.py
- python/cuspatial/cuspatial/tests/test_polyline_bounding_boxes.py
- python/cuspatial/cuspatial/tests/test_shapefile_reader.py
- python/cuspatial/cuspatial/tests/test_spatial_join.py
- python/cuspatial/cuspatial/tests/test_spline_fit.py
- python/cuspatial/cuspatial/tests/test_trajectory.py
As of rapidsai/cudf#7495 the `cudf.tests.utils` module (and in particular the `assert_eq` function) are no longer part of the public API. This PR switches tests to use the public testing functions in the `cudf.testing` subpackage.
This PR is currently blocked by #430 and rapidsai/cudf#8646.
> Switch to using public cudf testing utilities

- python/cuspatial/cuspatial/_lib/interpolate.pyx
- python/cuspatial/cuspatial/_lib/polygon_bounding_boxes.pyx
- python/cuspatial/cuspatial/_lib/polyline_bounding_boxes.pyx
- python/cuspatial/cuspatial/_lib/quadtree.pyx
- python/cuspatial/cuspatial/_lib/spatial_join.pyx
- python/cuspatial/cuspatial/_lib/spatial_window.pyx
- python/cuspatial/cuspatial/_lib/trajectory.pyx
- python/cuspatial/cuspatial/core/gis.py
- python/cuspatial/cuspatial/core/indexing.py
- python/cuspatial/cuspatial/core/interpolate.py
- python/cuspatial/cuspatial/core/spatial_join.py
- python/cuspatial/cuspatial/core/spatial_window.py
- python/cuspatial/cuspatial/core/trajectory.py
- python/cuspatial/cuspatial/geometry/geodataframe.py
rapidsai/cudf#8687 changes the internals of cuDF and removes the means by which libcudf table objects are converted to cuDF Frames. This PR should be merged after that one to match those APIs. I have verified locally that this PR's Cython code compiles and runs against that branch of cuDF.
> Update cudf table apis

- cpp/CMakeLists.txt
Previously on CentOS machines the CMake files would be placed into `lib64`, and `libcuspatial` would be in `lib` breaking everything. Since Conda only supports packages in `lib` ensure everything is placed there no matter
the distro.
> cuspatial installed CMake files use the same destination as libcuspatial

- python/cuspatial/cuspatial/core/indexing.py
- python/cuspatial/cuspatial/core/trajectory.py
> Remove cudf.core

- CHANGELOG.md
- cpp/CMakeLists.txt
This PR fixes the merge conflicts in `CHANGELOG.md` for the latest forward-merger PR.
> Fix Forward-Merge Conflicts [skip ci]

- CHANGELOG.md
- cpp/CMakeLists.txt
Forward-merge triggered by push to `branch-21.08` that creates a PR to keep `branch-21.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-21.08 to branch-21.10 [skip gpuci]

- cpp/cmake/Modules/ConfigureCUDA.cmake
- cpp/src/interpolate/cubic_spline.cu
- cpp/src/join/quadtree_poly_filtering.cu
- cpp/src/spatial/haversine.cu
- cpp/src/trajectory/trajectory_bounding_boxes.cu
- cpp/src/trajectory/trajectory_distances_and_speeds.cu
- python/cuspatial/setup.py
Make `nvcc` warnings into errors, fix new errors.
> [FIX] NVCC warnings are errors

- conda/recipes/libcuspatial/meta.yaml
This PR updates the `conda` recipe build strings and `cudatoolkit` version specifications as part of the Enhanced Compatibility efforts.
The build strings have been updated to only include the major CUDA version (i.e. `librmm-21.12.00a-cuda11_gc781527_12.tar.bz2`) and the `cudatoolkit` version specifications will now be formatted like `cudatoolkit >=x,<y.0a0` (i.e. `cudatoolkit >=11,<12.0a0`).
Moving forward, we'll build the packages with a single CUDA version (i.e. `11.4`) and test them in environments with different CUDA versions (i.e. `11.0`, `11.2`, `11.4`, etc.).
> Update `conda` recipes for Enhanced Compatibility effort

- conda/recipes/libcuspatial/meta.yaml
Forward-merge triggered by push to `branch-21.12` that creates a PR to keep `branch-22.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-21.12 to branch-22.02 [skip gpuci]

- conda/environments/cuspatial_dev_cuda11.0.yml
- conda/environments/cuspatial_dev_cuda11.1.yml
- conda/environments/cuspatial_dev_cuda11.2.yml
- cpp/scripts/run-clang-format.py
This upgrade is required to be in-line with: rapidsai/cudf#9716
Depends on: rapidsai/integration#390
> [REVIEW] Upgrade `clang` to `11.1.0`

- ci/cpu/prebuild.sh
Now that we only do `11.5` builds for RAPIDS, the `DEFAULT_CUDA_VER` variable in `ci/cpu/prebuild.sh` should be set to `11.5` so that the rest of the logic in the file works correctly.
> Update DEFAULT_CUDA_VER in ci/cpu/prebuild.sh

- cpp/.clang-format
- cpp/src/io/shp/polygon_shapefile_reader.cpp
- cpp/tests/interpolate/cubic_spline_test.cpp
It was recently noticed that the `IncludeCategories`:
```
IncludeCategories:
- Regex:           '^<ext/.*\.h>'
Priority:        2
- Regex:           '^<.*\.h>'
Priority:        1
- Regex:           '^<.*'
Priority:        2
- Regex:           '.*'
Priority:        3
```
In the `.clang-format` are not really necessary as `ext` has no meaning in RAPIDS. This PR removes these.
Note these changes are being made in all repos:
* `cudf`: https://github.com/rapidsai/cudf/pull/9876
* `rmm`: https://github.com/rapidsai/rmm/pull/933
* `cuml`: https://github.com/rapidsai/cuml/pull/4438
* `cugraph`: https://github.com/rapidsai/cugraph/pull/1987
> Remove `IncludeCategories` from `.clang-format`

- cpp/src/spatial/lonlat_to_cartesian.cu
One file in libcuspatial used `CUDA_HOST_DEVICE` from cudf/types.hpp instead of just `__device__ inline`, which is all it needed.  rapidsai/cudf#9797 changed the name of the macro, which broke the build.
This trivial PR fixes it and removes that particular unnecessary dependency.
> Remove use of libcudf's CUDA_HOST_DEVICE macro

- cpp/benchmarks/CMakeLists.txt
- cpp/tests/CMakeLists.txt
This PR adds a CMake `install` rule for test targets. This step is a prerequisite to being able to package tests in their own `conda` package, which will enable us to deprecate _Project Flash_.
> Add CMake `install` rule for tests

- cpp/include/cuspatial/spatial_join.hpp
Fixes #489 by swapping the order of the documented return values.
> Fix documentation of return type of quadtree_point_in_polygon

- conda/environments/cuspatial_dev_cuda11.0.yml
- conda/environments/cuspatial_dev_cuda11.1.yml
- conda/environments/cuspatial_dev_cuda11.2.yml
Forward-merge triggered by push to `branch-22.04` that creates a PR to keep `branch-22.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.04 to branch-22.06 [skip gpuci]

- ci/cpu/build.sh
- ci/cpu/upload.sh
- ci/gpu/build.sh
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/build.sh
- conda/recipes/libcuspatial/conda_build_config.yaml
- conda/recipes/libcuspatial/install_libcuspatial.sh
- conda/recipes/libcuspatial/install_libcuspatial_tests.sh
- conda/recipes/libcuspatial/meta.yaml
Add a `libcuspatial-tests` package to the `libcuspatial` recipe:
- This is a prerequisite for removing "Project Flash" from our build/CI scripts.
- The `libcuspatial-tests` package was added as an additional output to the existing `libcuspatial` recipe (which was renamed to `libcuspatial-split`)
> Add libcuspatial-tests package

- cpp/include/cuspatial/point_in_polygon.hpp
- python/cuspatial/cuspatial/core/gis.py
Partially addresses #492.
Adds notes to the Python and C++ documentation explaining that behavior is undefined if there are rings in `poly_ring_offsets` that are not referenced by `poly_offsets`
> Improve point_in_polygon documentation regarding poly_ring_offsets

- cpp/CMakeLists.txt
This PR allows building libcuspatial static libs via CMake option `-DBUILD_SHARED_LIBS=ON|OFF`.
Depends on https://github.com/rapidsai/cudf/pull/10545
> [FEA] Enable building static libs

- .pre-commit-config.yaml
This PR adds clang format to pre-commit hook.
closes #503
> Add clang-format to pre-commit hook

- cpp/benchmarks/synchronization/synchronization.cpp
- cpp/include/cuspatial/error.hpp
- cpp/src/interpolate/cubic_spline.cu
- cpp/src/join/quadtree_point_to_nearest_polyline.cu
- cpp/src/spatial/hausdorff.cu
- cpp/src/trajectory/trajectory_bounding_boxes.cu
- cpp/src/trajectory/trajectory_distances_and_speeds.cu
Following https://github.com/rapidsai/cudf/pull/10589, this PR removes the dependency to `cudf::CUDA_TRY` and introduces `CUSPATIAL_CUDA_TRY`.
Contributes to #474
> Replace `CUDA_TRY` with `CUSPATIAL_CUDA_TRY`

- python/cuspatial/cuspatial/core/gis.py
Since the units returned are in kilometers, I added that to the docstring so it appears in documentation. Closes #137.
> add units to haversine distance docstring

- cpp/CMakeLists.txt
- cpp/cmake/thirdparty/CUSPATIAL_GetCUDF.cmake
This PR contains three fixes to how libcuspatial handles dependencies to enable its inclusion into other projects:
1. GDAL is now exported as a global target so that consumers automatically see the library in addition to inheriting the dependency.
2. cudf is now part of the build and export set for libcuspatial so that consumers can inherit the dependency.
3. cudftestutil is included in the export set and exported as a global target iff cuspatial is being built with tests. This change ensures that when tests are not being built cuspatial can be built against a libcudf that also does not have tests built.
> Fix various issues with CMake exports

- conda/recipes/cuspatial/conda_build_config.yaml
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/conda_build_config.yaml
- conda/recipes/libcuspatial/meta.yaml
This PR enables the usage of conda compilers to build conda packages. This is required to use `mambabuild`
> Use conda compilers

- conda/recipes/cuspatial/conda_build_config.yaml
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/conda_build_config.yaml
- conda/recipes/libcuspatial/meta.yaml
Forward-merge triggered by push to `branch-22.06` that creates a PR to keep `branch-22.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.06 to branch-22.08 [skip gpuci]

- cpp/CMakeLists.txt
This PR changes the CMake configuration to use `rapids_cmake_install_lib_dir` to determine the OS-specific installation directory rather than hardcoding `lib`. I also removed the unused `INSTALL_CONFIGDIR` variable.
> Fix library directory for installation

- python/cuspatial/CMakeLists.txt
Since `python/cuspatial/CMakeLists.txt` was just introduced in the last release and is forward merged to this one, version bumper was not run on this file. Thus this is manually bumped. In future release this should be handled by https://github.com/rapidsai/cuspatial/blob/47ba833a139466028c8a756cc865b7c76d8ec586/ci/release/update-version.sh#L42
> Bump cuspatial python version in scikit-build

- build.sh
- ci/gpu/build.sh
- conda/recipes/cuspatial/build.sh
Discussions with the team indicated a general preference for having build.sh default to finding the C++ library by default (and erroring if one is not found) rather than building a new copy of libcuspatial when building cuspatial Python. This PR also avoids shadowing the `CMAKE_ARGS` environment variable in build.sh, which is important for conda-forge compatibility.
> Change build.sh to find C++ library by default and avoid shadowing CMAKE_ARGS

- CHANGELOG.md
> Fix failed automerge 22.06 into 22.08

- cpp/include/cuspatial/constants.hpp
- cpp/include/cuspatial/coordinate_transform.hpp
- cpp/include/cuspatial/cubic_spline.hpp
- cpp/include/cuspatial/cuda_utils.hpp
- cpp/include/cuspatial/cusparse_error.hpp
- cpp/include/cuspatial/detail/cubic_spline.hpp
- cpp/include/cuspatial/detail/utility/linestring.cuh
- cpp/include/cuspatial/detail/utility/traits.hpp
- cpp/include/cuspatial/distances/linestring_distance.hpp
- cpp/include/cuspatial/error.hpp
- cpp/include/cuspatial/experimental/hausdorff.cuh
- cpp/include/cuspatial/hausdorff.hpp
- cpp/include/cuspatial/haversine.hpp
- cpp/include/cuspatial/point_in_polygon.hpp
- cpp/include/cuspatial/point_quadtree.hpp
- cpp/include/cuspatial/polygon_bounding_box.hpp
- cpp/include/cuspatial/polyline_bounding_box.hpp
- cpp/include/cuspatial/shapefile_reader.hpp
- cpp/include/cuspatial/spatial_join.hpp
- cpp/include/cuspatial/spatial_window.hpp
- cpp/include/cuspatial/trajectory.hpp
- cpp/include/doxygen_groups.h
A recent change to libcudf removed a forward declaration and/or RMM header includes, and cuSpatial was errantly relying on these to get the definitions of `device_memory_resource` and `get_current_device_resource()`. 
This PR fixes that by adding missing includes of `rmm/mr/device/per_device_resource.hpp` in several files. It also generally cleans up include ordering and spacing, and adds a few missing copyright headers.
> Add missing rmm includes

- build.sh
- conda/recipes/libcuspatial/build.sh
This PR adds the ability to build benchmarks to build.sh, and passes the necessary option through from the conda build.sh. This change ensures that benchmarks must be able to build against changes in new PRs.
> Build benchmarks in CI

- cpp/benchmarks/CMakeLists.txt
- cpp/benchmarks/pairwise_linestring_distance.cu
- cpp/benchmarks/spatial_window.cu
- cpp/benchmarks/utility/random.cuh
- cpp/include/cuspatial/spatial_window.hpp
This currently calls the cuDF-based C++ API for `points_in_spatial_window`, in order to capture "before refactoring" throughput of the API. I plan to also run the post-refactoring version, and then update the benchmark to run the refactored API in order to not depend on libcudf in this benchmark.
> Add benchmark for points_in_spatial_window

- notebooks/nyc_taxi_years_correlation.ipynb
This PR fixes both broken links for the NYC 2016 and NYC 2017 datasets and reran the notebooks under 22.08.
> [skip ci] Fix Broken Link in NYC Taxi Notebook

- conda/recipes/cuspatial/conda_build_config.yaml
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/conda_build_config.yaml
This PR bumps the version of `gdal` that's being used in an attempt to resolve some conda-solve issues in our images.
> Bump `gdal` version

- cpp/benchmarks/pairwise_linestring_distance.cu
This PR fixes the following compile error:
```
pairwise_linestring_distance.cu (80): error: too many initializer values
detected during:
instantiation of "std::tuple<rmm::device_vector<cuspatial::cartesian_2d<T>>, rmm::device_vector<int32_t>> generate_linestring(int32_t, int32_t, T, cuspatial::cartesian_2d<T>) [with T=float]" 
```
> [FIX] Fix compile error in distance benchmark

- cpp/benchmarks/pairwise_linestring_distance.cu
- cpp/benchmarks/points_in_range.cu
- cpp/include/cuspatial/experimental/detail/hausdorff.cuh
- cpp/include/cuspatial/experimental/detail/linestring_distance.cuh
- cpp/include/cuspatial/experimental/detail/point_distance.cuh
- cpp/include/cuspatial/experimental/detail/points_in_range.cuh
- cpp/src/join/detail/point.cuh
- cpp/src/join/quadtree_point_to_nearest_polyline.cu
- cpp/src/trajectory/trajectory_distances_and_speeds.cu
- cpp/tests/experimental/spatial/coordinate_transform_test.cu
- cpp/tests/experimental/spatial/hausdorff_test.cu
- cpp/tests/experimental/spatial/point_distance_test.cu
This PR cherry-picked @bdice 45787e8 to include missing headers after updating CI to thrust 1.17, because the original PR that includes this commit may take extra time. This should unblock CI.
> Add Missing Thrust Headers for Thrust 1.17

- cpp/doc/DEVELOPER_GUIDE.md
- cpp/doc/libcuspatial_refactoring_guide.md
- cpp/include/cuspatial/experimental/detail/coordinate_transform.cuh
- cpp/include/cuspatial/experimental/detail/hausdorff.cuh
- cpp/include/cuspatial/experimental/detail/haversine.cuh
- cpp/include/cuspatial/experimental/detail/linestring_distance.cuh
- cpp/include/cuspatial/experimental/detail/point_distance.cuh
- cpp/include/cuspatial/experimental/detail/point_in_polygon.cuh
- cpp/include/cuspatial/experimental/detail/point_linestring_distance.cuh
- cpp/include/cuspatial/experimental/detail/points_in_range.cuh
- cpp/include/cuspatial/experimental/haversine.cuh
- cpp/include/cuspatial/experimental/type_utils.hpp
- cpp/include/cuspatial/traits.hpp
- cpp/include/cuspatial/vec_2d.hpp
- cpp/tests/experimental/spatial/hausdorff_test.cu
- cpp/tests/experimental/spatial/haversine_test.cu
- cpp/tests/experimental/spatial/linestring_distance_test.cu
- cpp/tests/experimental/spatial/point_distance_test.cu
- cpp/tests/experimental/spatial/point_linestring_distance_test.cu
- cpp/tests/experimental/spatial/points_in_range_test.cu
- cpp/tests/utility/vector_equality.hpp
* Expands the test utility `expect_vector_equivalent` to support comparing vectors of `vec_2d<T>` with approximate comparison of floating point equality (using GTEST functionality). This function now also explicitly copies all vectors to the host for comparison.
* Updates various tests to use the utility instead of directly calling `EXPECT_EQ`.
* Moves traits.hpp to top-level include directory and moves all traits helpers out of `detail` namespace so they are more easily used in tests and user code.
TODO: 
~- [ ] `coordinate_transform_test` fails with this change, so I have not committed it. Something is different with `EXPECT_EQ` and this function for that test. Investigating.~  This will be fixed in a followup PR -- we discovered the test is flawed.
> Expand expect_vector_equivalent to handle std::vector of vec_2d<T> and move traits out of detail

- conda/recipes/cuspatial/conda_build_config.yaml
- conda/recipes/libcuspatial/conda_build_config.yaml
@beckernick report's a GDAL version conflict with cuda. We're pinned at GDAL 3.4 and TensorFlow and other libs have already updated to GDAL 3.5. Let's update that here.
Fixes https://github.com/rapidsai/cuspatial/issues/674 and depends on https://github.com/rapidsai/integration/pull/533
> Update to the latest version 3 of GDAL.

- cpp/include/cuspatial/shapefile_reader.hpp
- cpp/src/io/shp/polygon_shapefile_reader.cpp
- cpp/src/io/shp/polygon_shapefile_reader.cu
- cpp/tests/io/shp/polygon_shapefile_reader_test.cpp
- python/cuspatial/cuspatial/_lib/cpp/shapefile_reader.pxd
- python/cuspatial/cuspatial/_lib/shapefile_reader.pyx
- python/cuspatial/cuspatial/core/_column/geocolumn.py
- python/cuspatial/cuspatial/core/geoseries.py
- python/cuspatial/cuspatial/io/shapefile.py
- python/cuspatial/cuspatial/tests/test_geoseries.py
- python/cuspatial/cuspatial/tests/test_shapefile_reader.py
This useful PR adds a `GeoSeries` constructor for the tuple returned by `read_polygon_shapefile`. Now users can say
```py
geoseries = cuspatial.GeoSeries(cuspatial.read_polygon_shapefile('the_shapefile'))
```
and load the data directly into GeoArrow.
This PR touches many files because I add a `reversed` argument to python and C++ so that the user can swap back and forth if they desire. This was required because the original implementation was reverse-ordering the polygons, which does not match GeoPandas results when reading a shapefile. Now it does, and is tested in both configurations.
Closes #668.
> [FEA] Integrate `GeoSeries` with `read_polygon_shapefile`

- cpp/CMakeLists.txt
This PR ensures cuSpatial statically links all the CUDA toolkit libraries (not just `cudart`) if a user enables `CUDA_STATIC_RUNTIME`.
> [FEA] Statically link all CUDA toolkit libraries

- cpp/include/cuspatial/constants.hpp
- cpp/include/cuspatial/experimental/detail/coordinate_transform.cuh
- cpp/tests/experimental/spatial/coordinate_transform_test.cu
Converting from `EXPECT_EQ` to `expect_vector_equivalent` (#669) caused `coordinate_transform_test` to fail due to floating point differences. It's strange that it passed with exact equality testing (perhaps a problem in Thrust?). In any case, this fixes the test data generation and DRYs up the tests a bit.
> Fix and tidy coordinate_transform_test

- python/cuspatial/cuspatial/core/geodataframe.py
This PR follows up https://github.com/rapidsai/cudf/pull/11687 to adapt to the change to `_copy_type_metadata` interface. This PR should unblock CI.
> Rewrite `copy_type_metadata` to reuse the inherited method and handle geocolumns specifically.

- conda/environments/cuspatial_dev_cuda11.0.yml
- conda/environments/cuspatial_dev_cuda11.1.yml
- conda/environments/cuspatial_dev_cuda11.2.yml
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/conda_build_config.yaml
- cpp/CMakeLists.txt
- java/src/main/native/CMakeLists.txt
- python/cuspatial/CMakeLists.txt
- python/cuspatial/pyproject.toml
With rapids-cmake now requiring CMake 3.23.1 update consumers to correctly express this requirement
> Document that minimum required CMake version is now 3.23.1

- cpp/doc/BENCHMARKING.md
- cpp/doc/TESTING.md
Contributes to #598. Adds `cpp/doc/TESTING.md` and `cpp/doc/BENCHMARKING.md`, the remaining parts of the libcuspatial C++ developer documentation. These documents cover unit testing and unit benchmarking best practices, respectively.
> Add TESTING.md and BENCHMARKING.md

- docs/source/api_docs/geopandas_compatibility.rst
- python/cuspatial/cuspatial/core/geodataframe.py
- python/cuspatial/cuspatial/core/geoseries.py
- python/cuspatial/cuspatial/core/spatial/distance.py
- python/cuspatial/cuspatial/core/trajectory.py
A few old issues that are tasked for `22.10` involve fixing documentation that is incorrect. I worked through the existing nightly docs and executed all of the code samples, fixing and improving anything that had incorrect outputs or inputs.
closes #460
closes #63
> Fix all unexecutable code examples I can find.

- cpp/CMakeLists.txt
- cpp/doc/DOCUMENTATION.md
Adds the C++ `DOCUMENTATION.md`, covering the use of Doxygen for documenting the code. Copied mostly from libcudf.
Contributes to #598
> Add DOCUMENTATION.md

- docs/source/api_docs/trajectory.rst
- docs/source/developer_guide/library_design.md
This PR fixes some render issue with `library_design.md`, adds links to c++ documentation (maybe changed after merging [673](https://github.com/rapidsai/cuspatial/pull/673))
> Add C++ doc links to `library_design.md` and minor documentation fixes

- python/cuspatial/cuspatial/_lib/utils.pyx
Fixes a bug in the cdef function when `pyoptcol` is `None` and gets mishandled (raised as error). This error is captured in one of the pytests for `point_linestring_distance`. However, due to the cdef function is missing the `except` keyword, the exception gets ignored by the python interpreter and not reraised.
> `unwrap_pyoptcol` is missing `except` keyword that causes exceptions ignored, fixes function bug

- python/cuspatial/cuspatial/core/_column/geocolumn.py
- python/cuspatial/cuspatial/core/geoseries.py
- python/cuspatial/cuspatial/tests/test_geodataframe.py
- python/cuspatial/cuspatial/tests/test_geoseries.py
Forward-merge triggered by push to `branch-22.10` that creates a PR to keep `branch-22.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.10 to branch-22.12 [skip gpuci]

- docs/source/developer_guide/index.md
- docs/source/developer_guide/library_design.md
This PR moves the library wide overview section to top level `developer guide`. And updates link to c++ developer guide. As of creation, the link to c++ developer guide is not published yet. Should verify before merge.
> Update link to c++ developer guide

- cpp/src/spatial/point_in_polygon.cu
- cpp/src/trajectory/trajectory_bounding_boxes.cu
- cpp/src/trajectory/trajectory_distances_and_speeds.cu
Currently cuspatial does not depend on anything defined in `cudf/detail/utility/cuda.cuh`, removing stale dependency.
> Remove `cudf/cuda.cuh` Dependency

- cpp/tests/utility/vector_equality.hpp
This PR augments Cuspatial Vector Equality Test Utility with an extra parameter to allow user pass in pre-defined absolute error.
In many cases, cuspatial has to compare results with external libraries such as shapely or gdal. Since cuspatial allows user to pick computation precision based on input data (not a bug!), requiring the result to match external libraries within 4ULP is often too stringent, as external libraries often perform computation in different precisions. Adding the flexibility to specifiy abs error in test utilitiy makes it easy for developer to pick desired error range based on specific use cases.
This PR also introduces a test macro that shows lineno of failed tests.
> Augment Cuspatial Test Utility to Allow User Specified Abs Error

- cpp/CMakeLists.txt
This is a port of https://github.com/rapidsai/cudf/pull/12067. 
Original post:
> The current version of nvbench is not compatible with the latest changes to fmt. This PR decouples us from needing to wait on upstreaming the compatibility changes to nvbench. These changes are necessary for building libcudf benchmarks until then.
> Force using old fmt in nvbench. 

- cpp/benchmarks/CMakeLists.txt
- cpp/benchmarks/floating_point_equality.cu
- cpp/include/cuspatial/detail/utility/floating_point.cuh
- cpp/tests/CMakeLists.txt
- cpp/tests/utility_test/test_float_equivalent.cu
This PR adds `float_eq_by_ulp` utility to allow practical near equality for floating point computation in device code.
In GIS application, near equal is often required due to rounding error of floating point and may wrong categorization of line collinearity or point on line test.
Using this test does not incur visible performance degradation:
```
$ python ~/scratch/nvbench/scripts/nvbench_compare.py naive.json ulp.json 
['naive.json', 'ulp.json']
|  FloatingPointType  |  NumFloats  |   Ref Time |   Ref Noise |   Cmp Time |   Cmp Noise |      Diff |   %Diff |  Status  |
|---------------------|-------------|------------|-------------|------------|-------------|-----------|---------|----------|
|         F32         |   100000    |   2.617 us |      55.95% |   2.478 us |      53.16% | -0.139 …
```
> Introduce ULP Based Floating Point Equality Test to Device Function

- cpp/benchmarks/pairwise_linestring_distance.cu
- cpp/include/cuspatial/detail/iterator.hpp
- cpp/include/cuspatial/detail/utility/linestring.cuh
- cpp/include/cuspatial/experimental/detail/geometry/linestring_ref.cuh
- cpp/include/cuspatial/experimental/detail/geometry_collection/multilinestring_ref.cuh
- cpp/include/cuspatial/experimental/detail/linestring_distance.cuh
- cpp/include/cuspatial/experimental/detail/ranges/multilinestring_range.cuh
- cpp/include/cuspatial/experimental/geometry/linestring_ref.cuh
- cpp/include/cuspatial/experimental/geometry_collection/multilinestring_ref.cuh
- cpp/include/cuspatial/experimental/geometry_collection/multipoint_ref.cuh
- cpp/include/cuspatial/experimental/linestring_distance.cuh
- cpp/include/cuspatial/experimental/ranges/multilinestring_range.cuh
- cpp/include/cuspatial_test/vector_factories.cuh
- cpp/src/spatial/linestring_distance.cu
- cpp/tests/experimental/spatial/linestring_distance_test.cu
- cpp/tests/utility/vector_equality.hpp
Note, this is the first part of `pairwise_linestring_distance` refactoring, part 1 of PR: https://github.com/rapidsai/cuspatial/pull/753
Depends on #752 
Contributes to https://github.com/rapidsai/cuspatial/issues/706, https://github.com/rapidsai/cuspatial/issues/703
Closes #745
> Refactor of `pairwise_linestring_distance` to use `multilinestring_range`, adds support to multilinestring distance

- python/cuspatial/cuspatial/core/geoseries.py
`cudf.merge` doesn't guarantee item ordering, an important feature of `loc`. This PR fixes that by adding a reordering step to post processing the merge.
Fixes https://github.com/rapidsai/cuspatial/issues/781
> Fix issue with `.loc` returning values out of order.

- python/cuspatial/cuspatial/core/geoseries.py
- python/cuspatial/cuspatial/core/spatial/distance.py
- python/cuspatial/cuspatial/core/spatial/nearest_points.py
- python/cuspatial/cuspatial/tests/conftest.py
- python/cuspatial/cuspatial/tests/test_geocolumn_accessor.py
- python/cuspatial/cuspatial/tests/test_geoseries.py
- python/cuspatial/cuspatial/tests/test_point_linestring_distance.py
Closes #771 
This PR modifies the production of `geometry_offset`, `part_offset`, and `ring_offset` by sampling the existing values in a `GeoSeries` before returning their various offsets. This has the effect of using `cudf.ListSeries` to re-pack any features into a new, dense `GeoColumn`, then returning the offsets based on it.
Previously, `GeoSeries` that had been modified by slicing would have the appearance of the sliced elements, but when `_offset` buffers were used they would return the full original offset buffer that the sliced `GeoSeries` had originated from. This was a problem because it made slicing useless for our algorithms.
I also modify the `core/spatial/distance.py` and `core/spatial/nearest_points.py` files to use `as_column(linestrings.lines.geometry_offset)` instead of …
> Better slicing via `union_offsets`

- .github/labeler.yml
This PR is part of a labeling cleanup and minimizaiton in cuSpatial. 
We have duplicate `cpp` and `c++` labels, but really they both refer to work on `libcuspatial`. Updating the labeler to reflect this.
> Labeler: Change cpp label to libcuspatial

- .github/labeler.yml
Forward-merge triggered by push to `branch-22.12` that creates a PR to keep `branch-23.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.12 to branch-23.02 [skip gpuci]

- conda/environments/cuspatial_dev_cuda11.5.yml
- conda/recipes/cuspatial/conda_build_config.yaml
- conda/recipes/libcuspatial/conda_build_config.yaml
This PR sets a maximum version pin for `gdal`. Recently, `gdal` version `3.6.0` was released, which has a different version number for the `libgdal` shared object (`libgdal.so.32` vs. `libgdal.so.31`).
Setting the max pin here will ensure that we use a consistent `libgdal` shared object version for building and at runtime.
This should solve the `ImportError: libgdal.so.32: cannot open shared object file: No such file or directory` errors that have been popping up in recent Jenkins logs.
> Set max version pin for `gdal`

- conda/environments/cuspatial_dev_cuda11.5.yml
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/conda_build_config.yaml
- python/cuspatial/pyproject.toml
Avoid CMake 3.25.0 as it has an issue that stops cmake execution on conda envs.
> Don't use CMake 3.25.0 as it has a FindCUDAToolkit show stopping bug

- cpp/include/cuspatial/detail/utility/linestring.cuh
- cpp/tests/experimental/operators/linestrings_test.cu
#778 introduced segment intersection primitive, but there's a subtle bug in the code. This PR fixes that.
> Fix a Bug in Segment Intersection Primitive

- cpp/tests/CMakeLists.txt
#773 added a test utility that checks floating point equality based on ULP difference. However, as a blinded file checkout in #786, the line that builds tests for the floating point utility is removed by mistake. This PR adds that back.
> Add Floating Point Equality Tests to Build List

- cpp/include/cuspatial/experimental/detail/indexing/construction/phase_2.cuh
- cpp/include/cuspatial/experimental/detail/point_quadtree.cuh
- cpp/include/cuspatial/experimental/point_quadtree.cuh
- cpp/include/cuspatial/point_quadtree.hpp
- cpp/include/cuspatial/spatial_join.hpp
- cpp/src/indexing/construction/point_quadtree.cu
- cpp/src/join/detail/intersection.cuh
- cpp/tests/experimental/indexing/point_quadtree_test.cu
- docs/source/api_docs/spatial.rst
- python/cuspatial/cuspatial/_lib/quadtree.pyx
- python/cuspatial/cuspatial/core/geoseries.py
- python/cuspatial/cuspatial/core/spatial/indexing.py
- python/cuspatial/cuspatial/core/spatial/join.py
- python/cuspatial/cuspatial/tests/spatial/indexing/test_indexing.py
* Aligns docstrings between C++ and Python
* Adds missing methods to Python docs
* Fixes #733 
* Fixes #397
> [FIX] Update quadtree spatial join docstrings

- python/cuspatial/cuspatial/tests/test_geodataframe.py
- python/cuspatial/cuspatial/tests/test_geoseries.py
Upstream in cudf the `memory_usage` method seems to have changed its reporting size slightly.
This breaks CI in cuSpatial. This PR changes the memory usage test result values to reflect the minor update in cudf.
> Update `memory_usage` with tweaked sizes

- cpp/include/cuspatial/experimental/detail/linestring_intersection_with_duplicates.cuh
- cpp/tests/experimental/spatial/linestring_intersection_with_duplicates_test.cu
This PR sorts the intersection result in `linestring_intersection_with_duplicate` test. If a pair has more than 1 intersection result (e.g. 2 intersecting points) the order of these geometries is non-deterministic. While this doesn't affect the semantic of the result, this makes tests flaky and may break CI. Thus in the tests we have to sort the result before testing. This PR adds the infrastructure to sort the results, as well as rearranging the order to some of the hard coded results.
> Fix: Sort Intersection Result by Keys in `intersection_with_duplicate` Test

- python/cuspatial/cuspatial/core/geoseries.py
- python/cuspatial/cuspatial/tests/test_align.py
Closes #848 
This PR fixes a bug with `align` so that slicing a `GeoSeries`, then calling a binpred with slices of the `GeoSeries` with unmatching indexes works. It also adds a few more valid tests.
As of this PR one test still fails, I'm working on it but it feels like a rabbit hole. I'm inclined to leave the case for later:
The case that doesn't work is the hardest case wherein two `GeoSeries` have different length as well as indexes in one that is not present in the other.
> Fix a bug preventing `align` from working with a basic slice.

- cpp/include/cuspatial_test/vector_equality.hpp
- cpp/tests/experimental/indexing/point_quadtree_test.cu
- cpp/tests/experimental/spatial/hausdorff_test.cu
- cpp/tests/experimental/spatial/haversine_test.cu
- cpp/tests/experimental/spatial/linestring_bounding_boxes_test.cu
- cpp/tests/experimental/spatial/linestring_intersection_intermediates_remove_if_test.cu
- cpp/tests/experimental/spatial/linestring_intersection_with_duplicates_test.cu
- cpp/tests/experimental/spatial/point_bounding_boxes_test.cu
- cpp/tests/experimental/spatial/point_distance_test.cu
- cpp/tests/experimental/spatial/point_linestring_distance_test.cu
- cpp/tests/experimental/spatial/point_linestring_nearest_points_test.cu
- cpp/tests/experimental/spatial/points_in_range_test.cu
- cpp/tests/experimental/spatial/polygon_bounding_boxes_test.cu
- cpp/tests/experimental/spatial/sinusoidal_projection_test.cu
- cpp/tests/experimental/trajectory/derive_trajectories_test.cu
- cpp/tests/experimental/trajectory/trajectory_distances_and_speeds_test.cu
Updates all header-only API tests to consistently use the `CUSPATIAL_EXPECT_VECTORS_EQUIVALENT` and `CUSPATIAL_EXPECT_VEC2D_PAIRS_EQUIVALENT` macros. 
Fixes #638. (However there wasn't really a correctness issue.)
> Use vector equivalence macros consistently in header-only API tests.

- .github/ISSUE_TEMPLATE/bug_report.yml
- print_env.sh
Closes #774 
- This PR adds the `print_env.sh` file from cudf to get specific environment information during bug reports. 
- The bug report template is also updated, requesting reporters to run the script and include its results.
> Add print_env.sh to improve bug reporting

- cpp/include/cuspatial/shapefile_reader.hpp
- docs/source/api_docs/io.rst
- docs/source/user_guide/cuspatial_api_examples.ipynb
- python/cuspatial/cuspatial/io/shapefile.py
cuSpatial's C++-based shapefile reader is limited. It can only load polygons (not multipolygons). It was written before cuSpatial supported GeoArrow data format and before it could ingest data from GeoPandas directly. It is better to use GeoPandas or other libraries to load data into cuSpatial. Dropping `read_polygon_shapefile` and its C++ implementation allows dropping the libcuspatial dependency on GDAL, which may help with publishing PIP wheels, which is a priority.
This PR simply adds deprecation warnings / decorators to the Python and C++ `read_polygon_shapefile` functions and documentation, and updates the Python user guide to mention deprecation.
The plan is to remove these functions and tests that depend on them in 23.04.
> Deprecate shapefile reader

- python/cuspatial/cuspatial/core/_column/geocolumn.py
- python/cuspatial/cuspatial/core/geodataframe.py
- python/cuspatial/cuspatial/tests/test_geodataframe.py
Certain cudf operations like `.merge` return a `cudf.DataFrame`, which then doesn't understand the `geometry` column contained within. Until we've worked out a way to build `ExtensionDtypes` for cudf, the `cudf.DataFrame` needs to be converted back to a `GeoDataFrame` for use with cuspatial. This PR adds a new valid constructor argument of type `cudf.DataFrame` to `__init__` for `GeoDataFrame`.
Closes #893
> Allow initialization of a `GeoDataFrame` using a `cudf.DataFrame`

- python/cuspatial/cuspatial/core/_column/geocolumn.py
- python/cuspatial/cuspatial/core/dtypes.py
- python/cuspatial/cuspatial/utils/column_utils.py
This PR fixes #888, raises when input is not an integer array.
This PR also fixes a bug in `_from_point_xy` where empty series other than points are incorrectly constructed. An empty linestring array should be properly nested with the leaf column containing 0 elements. Currently it is constructed as a flat array, resulting in a ill-constructed geocolumn.
> `_from_point_xy` improvements

- python/cuspatial/cuspatial/core/geoseries.py
- python/cuspatial/cuspatial/tests/test_geoseries.py
Closes #891 , fixes an issue in `point_indices`. Previously, the point indices are computed with the ring offset, but the target index is mean to denote the (multi)polygon index, so we need to compute an array of offset corresponding to geometry offset. This can be computed via nested gathers.
> Fix broken `point_indices` methods in `PolygonGeoColumnAccessor`

- python/cuspatial/benchmarks/api/bench_api.py
- python/cuspatial/benchmarks/conftest.py
- python/cuspatial/cuspatial/core/spatial/projection.py
- python/cuspatial/cuspatial/core/trajectory.py
- python/cuspatial/cuspatial/tests/spatial/projection/test_sinusoidal_projection.py
- python/cuspatial/cuspatial/tests/test_trajectory.py
This PR refactors API to accept GeoSeries input for projection and trajectory functions.
closes #949, closes #950, closes #951, closes #952
> Refactors API to accept GeoSeries input for projection and trajectory functions

- dependencies.yaml
This PR updates aarch64 dependencies to use GCC 11. Follow-up to #961.
> Update aarch64 to GCC 11

- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/meta.yaml
This PR ensures that the `AWS_SESSION_TOKEN` and `SCCACHE_S3_USE_SSL` environment variables are passed to our conda build process.
`AWS_SESSION_TOKEN` is necessary in order to support using temporary credentials via AWS STS (we recently adopted this method in CI).
`SCCACHE_S3_USE_SSL` has been reported to increase cache performance for S3.
> Pass `AWS_SESSION_TOKEN` and `SCCACHE_S3_USE_SSL` vars to conda build

- conda/recipes/libcuspatial/meta.yaml
- cpp/CMakeLists.txt
- cpp/cmake/thirdparty/get_gtest.cmake
This PR aims to fix broken C++ build.
> Attempt to Fix Broken C++ Build After `cudftestutil` is Made a Shared Lib

- docs/source/user_guide/cuspatial_api_examples.ipynb
closes #987
This PR adds the missing API example for `pairwise_linestring_intersection`
> Add `pairwise_linestring_intersection` example in user guide

- README.md
This fixes the link text for the linestring intersection function in the readme. In my haste to get the readme in, I failed to notice the link ate the link-text instead of auto updating like it usually does in the GitHub web ui.
> [DOC]: Fix linestring link in readme

- .github/workflows/pr.yaml
- .pre-commit-config.yaml
Similarly to these [cudf](https://github.com/rapidsai/cudf/pull/12819) and [cuml](https://github.com/rapidsai/cuml/pull/5246) PRs, this PR adds an entry to `.pre-commit-config.yaml` to run the [dependency-file-generator](https://github.com/rapidsai/dependency-file-generator).
It also adds an argument to the `rapidsai/shared-action-workflows/.github/workflows/checks.yaml` shared workflow to disable the `dependency-file-generator` from running in that shared workflow. This avoids having the `dependency-file-generator` run in two places since pre-commit is run in CI [here](https://github.com/rapidsai/cuspatial/blob/branch-23.04/ci/check_style.sh#L23).
> Add `dependency-file-generator` as `pre-commit` hook

- cpp/tests/experimental/spatial/hausdorff_test.cu
- cpp/tests/experimental/spatial/point_bounding_boxes_test.cu
- cpp/tests/experimental/trajectory/derive_trajectories_test.cu
- cpp/tests/experimental/trajectory/trajectory_distances_and_speeds_test.cu
- cpp/tests/utility_test/test_geometry_generators.cu
Fixes #1017. 
Reduces C++ gtest total time (on my PC) from 47.9 seconds to 20.08 seconds.
Several tests were running large datasets and combinations of size parameters that would be better to run as benchmarks rather than gtests. Reducing these by a factor of 10-100 saves a lot of development time and still exercises the code. In the case of `HausdorffTest/1.10000Spaces10Points (4850 ms)`, reducing it to 1000 spaces, 10 points reduced the time by nearly 100x, likely because it's $O(N^2)$. 
I modified any test that used close to 1s or more total time, since most column-API tests use under that, and most header-only tests use under 0.2s. 
| Test | Time Before (s) | Time After (s)  | Speedup |
|---|---|---|---|
| DERIVE_TRAJECTORIES_TEST_EXP | 14.49 | 0.27 | 53.7x |
| HAUSDORFF_TEST_EXP | …
> Reduce gtest times

- cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md
Fixes #1032 by using `<tt>\"</tt>` instead of `` `"` ``.
Also reflows some Markdown.
> Fix quotes in backticks in Developer Guide

- cpp/include/cuspatial/experimental/detail/distance_utils.cuh
- cpp/include/cuspatial/experimental/detail/linestring_polygon_distance.cuh
- cpp/include/cuspatial/experimental/detail/point_polygon_distance.cuh
- cpp/include/cuspatial/experimental/linestring_polygon_distance.cuh
- cpp/include/cuspatial_test/test_util.cuh
- cpp/include/cuspatial_test/vector_factories.cuh
- cpp/tests/CMakeLists.txt
- cpp/tests/experimental/range/multilinestring_range_test.cu
- cpp/tests/experimental/spatial/linestring_polygon_distance_test.cu
Forward-merge triggered by push to `branch-23.04` that creates a PR to keep `branch-23.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.04 to branch-23.06

- cpp/include/cuspatial/experimental/detail/distance_utils.cuh
- cpp/tests/experimental/spatial/point_polygon_distance_test.cu
This PR fixes #1042 . In `point_polygon_intersects`, the key comparator incorrectly uses the binary operator that's used for values.
> Bug Fix: point-in-multipolygon reduction using the wrong key-compare functor

- cpp/tests/experimental/spatial/pairwise_point_in_polygon_test.cu
use make_device_vector in pairwise_point_in_polygon_test
closes #825
> use make_device_vector in pairwise_point_in_polygon_test

- cpp/include/cuspatial/experimental/detail/linestring_intersection.cuh
- cpp/tests/experimental/spatial/linestring_intersection_test.cu
- cpp/tests/experimental/spatial/linestring_intersection_with_duplicates_test.cu
- python/cuspatial/cuspatial/tests/binops/test_intersections.py
This PR fixes a bug in `pairwise_linestring_intersection`, where `point_flags` is incorrectly used to remove points in points array due to leftover results from find_duplicate_points.
Previously, the code incorrectly  assumed that `point_flags` will always be written to prior to `merge_point_on_segment` kernel, however, this may not be true if the result segment array is empty, and the kernel launch could be evaded, leading to that the second `remove_if` operates on the "leftover" from the previous `point_flag` ramnant.
This fix is to only run segment cleanup kernels if there is at least one segment result in the output. This not only fixes #1067 , but also serve as an optimization to avoid unnecessary kernel launching.
It should be pointed out that the result from python isn't exactly …
> Bug fix in `pairwise_linestring_intersection`

- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/meta.yaml
This change passes through the value of `SCCACHE_S3_NO_CREDENTIALS` to our `conda` builds, enabling devs to utilize the `sccache` cache that's populated by CI when they are reproducing build issues locally as per [these](https://docs.rapids.ai/resources/reproducing-ci/) instructions.
> Enable sccache hits from local builds

- ci/release/update-version.sh
- conda/environments/all_cuda-118_arch-x86_64.yaml
- dependencies.yaml
This PR pins cuml dependency in notebook testing environment to nightlies as required in the CI environment.
> Pin cuml dependency in notebook testing environment to nightlies

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/recipes/libcuspatial/conda_build_config.yaml
- cpp/include/cuspatial_test/test_util.cuh
- cpp/tests/operators/linestrings_test.cu
- cpp/tests/trajectory/derive_trajectories_test.cu
- dependencies.yaml
Following Rapids-cmake bump to gtest 1.13.0 https://github.com/rapidsai/rapids-cmake/issues/400, this PR implements some custom out stream operator for more constrained ADL rules that 1.11+ uses.
> Bump Gtest version following Rapids-cmake change

- notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb
This PR improves the zipcode counting notebook by utilizing cudf string and list column methods to parse WKT as geometry column. This achieves 40X speed up comparing to parsing on host.
> Improve zipcode counting notebook by adding GPU backed WKT parser

- cpp/src/indexing/point_quadtree.cu
- cpp/src/intersection/linestring_intersection.cu
- cpp/src/join/quadtree_bbox_filtering.cu
- cpp/src/join/quadtree_point_in_polygon.cu
- cpp/src/join/quadtree_point_to_nearest_linestring.cu
- cpp/src/trajectory/derive_trajectories.cu
- cpp/tests/trajectory/test_derive_trajectories.cpp
- cpp/tests/trajectory/test_trajectory_bounding_boxes.cu
- cpp/tests/trajectory/test_trajectory_distances_and_speeds.cu
- docs/source/user_guide/cuspatial_api_examples.ipynb
Update `cudf::column` constructor args to match the changes in https://github.com/rapidsai/cudf/pull/13341.
Also corrects a minor issue in the docs, closes #1154.
> Fix `cudf::column` constructor args

- cpp/include/cuspatial/detail/distance/linestring_distance.cuh
- cpp/include/cuspatial/detail/distance/linestring_polygon_distance.cuh
- cpp/include/cuspatial/detail/distance/point_linestring_distance.cuh
- cpp/include/cuspatial/detail/distance/point_polygon_distance.cuh
- cpp/include/cuspatial/detail/distance/polygon_distance.cuh
- cpp/include/cuspatial/detail/kernel/pairwise_distance.cuh
Forward-merge triggered by push to `branch-23.06` that creates a PR to keep `branch-23.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.06 to branch-23.08

- ci/release/update-version.sh
- cpp/doxygen/Doxyfile
Updates `update-version.sh` to follow the pattern from https://github.com/rapidsai/cugraph/pull/3638
Required for `23.06` because `python/cuspatial/pyproject.py` does not exist thus breaking the script. This means any hotfixes to this version will have issues during release.
Also updates a version in `cpp/doxygen/Doxyfile` which was outdated.
Skipped CI since this script is not tested by CI.
> Fix update version

- ci/release/update-version.sh
> Forward merge `branch-23.06` into `branch-23.08`

- cpp/include/cuspatial/distance.cuh
This PR fixes a small typo in pairwise_linestring_distance
> Fix a small typo in pairwise_linestring_distance

- notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb
This PR fixes the usage of a small cudf string processing method. `regex` should be set to false for `.str.split` without
regex delimiter. In addition, adds credit to authors.
> Add author credit to zipcode counting notebook, fix cudf string processing argument

- conda/recipes/cuspatial/meta.yaml
The Python packages had the same `build/string` for CUDA 11 & 12 builds, which resulted in only one of these builds being uploaded (appears to be CUDA 11 since those builds were a bit faster). To distinguish these and ensure both CUDA 11 & 12 packages are uploaded, add the CUDA major version to the `build/string`.
<hr>
> Add CUDA major to `cuspatial`'s `build/string`

- cpp/src/distance/haversine.cu
- cpp/src/trajectory/derive_trajectories.cu
rapidsai/cudf#13629 added stream argument to all copying APIs. This fix makes sure cuspatial usage is compliant.
> Add streams to allocate_like call

- python/cuspatial/cuspatial/core/geodataframe.py
- python/cuspatial/cuspatial/core/geoseries.py
As title, addresses upstream cudf change rapidsai/cudf#13534.
Fixes #1222
> Update GeoDataFrame to Use the Structured GatherMap Class

- cpp/CMakeLists.txt
This PR updates cuspatial to use rapids-cmake to supply its Google Benchmark (gbench, also called `benchmark`) dependency.
Currently I am unable to build cuspatial in a rapids-compose environment with cudf because cuspatial and cudf expect different versions of `benchmark` (rapids-cmake and cudf use 1.8.0, while cuspatial is pinned at 1.5.3).
> Use rapids-cmake to supply Google Benchmark library.

- cpp/cuproj/CMakeLists.txt
Follow-up to #1224 for cuproj.
> Use Google Benchmark from rapids-cmake in cuproj.

- cpp/cuproj/CMakeLists.txt
Forward-merge triggered by push to `branch-23.08` that creates a PR to keep `branch-23.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.08 to branch-23.10

- python/cuspatial/cuspatial/core/binops/distance_dispatch.py
- python/cuspatial/cuspatial/core/geoseries.py
- python/cuspatial/cuspatial/tests/conftest.py
- python/cuspatial/cuspatial/tests/spatial/distance/test_distance.py
- python/cuspatial/cuspatial/tests/test_geoseries.py
closes #759
This PR adds `geoseries.distance`, computing distances between two geoseries.
Benchmarking distance API is a complicated task. Below I present the benchmark of a simplest case: distance between a pair of point geoseries. geopandas is also quite fast when computing simple point distances, througput peaks at 1e5 and gets surpassed by cuspatial for larger data sizes. Both geopandas and cuspatial sees performance drop when dealing with index alignments.
TODO:
> Add `geoseries.distance`

- .github/workflows/test.yaml
Follow up to #1217 to enable wheels testing for `cuproj` for nightly tests.
Should fix issue seen [here](https://github.com/rapidsai/cuspatial/actions/runs/5748659541/job/15581971500)
> Update nightly wheel tests for cuproj

- ci/test_notebooks.sh
- notebooks/binary_predicates.ipynb
Closes https://github.com/rapidsai/cuspatial/issues/1138
Closes https://github.com/rapidsai/cuspatial/issues/1141 [here](https://github.com/rapidsai/cuspatial/pull/1156/files#diff-c522c9afb3364b1aed2b2589c0d0c260dbc634bc54844536b1d382cecb92bf29R112)
Depends on https://github.com/rapidsai/cuspatial/pull/1152
Depends on https://github.com/rapidsai/cuspatial/pull/1064
Please direct your attention [to the notebook](https://github.com/rapidsai/cuspatial/pull/1156/files#diff-cc4c516f63efa822793d75315c1b28a04bad6c9efc6fd2bdcac5cc30b05d14dd) since the dependencies and delayed state of CI issues over this week have put a lot of files into this PR.
This notebook demonstrates cuSpatial's new binary predicates on large datasets, benchmarking and comparing against the host implementation on GeoPandas. …
> Binary Predicates Introduction and Benchmark Notebook

- .pre-commit-config.yaml
- cpp/scripts/run-clang-format.py
This PR updates cuspatial to use clang 16.0.6. This aligns with the major version 16 being used elsewhere in RAPIDS, with a bugfix version that avoids clang-format issues around `*` multiplication operators.
> Update to clang 16.0.6.

- python/cuspatial/benchmarks/api/bench_api.py
- python/cuspatial/benchmarks/conftest.py
closes #994 
There are primitive benchmark results for `GeoSeries.distance` in #1231. This PR plans to add more benchmark coverage:
TODO:
> Benchmark `GeoSeries.Distance`

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-120_arch-x86_64.yaml
- dependencies.yaml
Adds `curl` as a notebook dependency which is used in two notebooks: `notebooks/nyc_taxi_years_correlation.ipynb` & `notebooks/ZipCodes_Stops_PiP_cuSpatial.ipynb` (https://github.com/search?q=repo%3Arapidsai%2Fcuspatial+curl&type=code).
This is similar to https://github.com/rapidsai/cugraph/pull/3918 and will fix errors in the notebooks tests in `rapidsai/docker`.
> Add `curl` for notebook testing

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-120_arch-x86_64.yaml
- dependencies.yaml
Forward-merge triggered by push to `branch-23.10` that creates a PR to keep `branch-23.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.10 to branch-23.12

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- README.md
- ci/release/update-version.sh
- dependencies.yaml
- python/cuproj/pyproject.toml
- python/cuspatial/pyproject.toml
This PR switches back to using `branch-23.12` for CI workflows because the CUDA 12 ARM conda migration is complete.
> Use branch-23.12 workflows.

- python/cuspatial/cuspatial/core/spatial/distance.py
- python/cuspatial/cuspatial/tests/spatial/distance/test_hausdorff_distance.py
This PR revises the gold result of hausdorff empty input test to address
an upstream change in cudf.
> Fix broken hausdorff test

- ci/build_wheel_cuspatial.sh
- python/cuspatial/CMakeLists.txt
- python/cuspatial/cmake/Modules/WheelHelpers.cmake
Some minor simplification in advance of the scikit-build-core migration to better align wheel and non-wheel Python builds. Additionally, this PR simplifies handling of the nvcomp targets and their installation.
> Remove CUSPATIAL_BUILD_WHEELS and standardize Python builds

- conda/recipes/cuproj/conda_build_config.yaml
Currently `pyproj` is still pinned to `proj` 9.3.0 (for [example]( https://github.com/conda-forge/pyproj-feedstock/blob/1cd88219a34c40265a8f70384476ce6c90e1ac45/.ci_support/linux_64_numpy1.26python3.12.____cpython.yaml#L19-L20 )). However `proj` recently released `9.3.1` ( https://github.com/conda-forge/proj.4-feedstock/pull/140 ), which `cuproj` is pulling in at the moment. Since `proj` [pins to the patch version in its `run_exports`]( https://github.com/conda-forge/proj.4-feedstock/blob/332baf3b6a739377f5e5cf65d9e9297d02a6ddf3/recipe/meta.yaml#L15-L18 ), building against `9.3.1` means `cuproj` would need exactly `9.3.1` at runtime. This makes it incompatible with everything else, which is still pinned to `proj` `9.3.0`. Embedded screenshot below to highlight this
<details>
</details>
So …
> Pin `proj` to `9.3.0` in `cuproj`

- conda/recipes/cuproj/conda_build_config.yaml
> [HOTFIX] v23.12.01

- conda/recipes/cuproj/meta.yaml
This updates cuproj's conda recipe to use `cython >=3.0.0` to align with other RAPIDS packages.
> Use Cython 3 for cuproj.

- cpp/include/cuspatial/column/geometry_column_view.hpp
- cpp/include/cuspatial/detail/index/construction/phase_1.cuh
- cpp/include/cuspatial/detail/join/quadtree_bbox_filtering.cuh
- cpp/include/cuspatial/detail/join/quadtree_point_to_nearest_linestring.cuh
- cpp/include/cuspatial/detail/point_quadtree.cuh
- cpp/include/cuspatial_test/vector_factories.cuh
- cpp/tests/distance/hausdorff_test.cu
- cpp/tests/distance/haversine_test.cu
- cpp/tests/distance/linestring_distance_test.cu
- cpp/tests/trajectory/trajectory_distances_and_speeds_test.cu
- cpp/tests/trajectory/trajectory_test_utils.cuh
This PR makes cuspatial compatible with Thrust 2 by adding `cuda::proclaim_return_type`, but does not upgrade the version of Thrust/CCCL just yet. Currently we use libcudacxx 2.1.0, which makes `cuda::proclaim_return_type` available, but we still use Thrust 1.17.2 which doesn't require device lambdas to have proclaimed return types. This diff is separated out from #1096. I will create a separate PR which contains only packaging changes / version updates for the CCCL 2 migration. This PR is **nonbreaking**, while the second PR will be **breaking**.
> Use cuda::proclaim_return_type on device lambdas.

- python/cuspatial/cuspatial/core/_column/geocolumn.py
- python/cuspatial/cuspatial/core/binops/distance_dispatch.py
- python/cuspatial/cuspatial/core/binops/intersection.py
This PR fixes failures which were caused becuase cuspatial uses an internal method of cudf that was removed in https://github.com/rapidsai/cudf/pull/14689. The errors can be fixed by replacing those usages in the same fashion as was done internally in that cudf PR.
cc @vyasr
> Update usage of cudf.core.column.arange to cudf.core.column.as_column

- cpp/benchmarks/fixture/benchmark_fixture.hpp
- cpp/benchmarks/fixture/rmm_pool_raii.hpp
- cpp/cuproj/benchmarks/fixture/benchmark_fixture.hpp
- cpp/src/join/quadtree_point_in_polygon.cu
- cpp/tests/intersection/linestring_intersection_test.cu
This PR fixes up cuSpatial to avoid usage that will soon be deprecated in RMM.
Depends on rapidsai/rmm#1417
Fixes #1318
> Add explicit initial size to all pools and avoid RMM detail APIs

- python/cuspatial/cuspatial/core/spatial/distance.py
This private API will be removed in 24.02
> Replace cudf _from_columns with a public API

- docs/source/developer_guide/build.md
Reading through the docs at https://docs.rapids.ai/api/cuspatial/nightly/developer_guide/build/, I noticed what looked like a formatting mistake:
This fixes it.
> fix formatting in developer guide

- ci/release/update-version.sh
- dependencies.yaml
Contributes to https://github.com/rapidsai/build-planning/issues/13.
Updates `update-version.sh` to correctly handle RAPIDS dependencies like `cudf-cu12==24.2.*`.
This also pulls in some dependency refactoring originally added in #1320, which allows greater use of dependencies.yaml globs (and therefore less maintenance effort to support new CUDA versions).
The portability of this updated `sed` command was tested here: https://github.com/rapidsai/cudf/pull/14825#issuecomment-1904735849.
In this repo, I ran the following:
```shell
./ci/release/update-version.sh '23.12.00'
git diff
./ci/release/update-version.sh '24.04.00'
git diff
```
Confirmed that that first `git diff` changed all the things I expected, and that second one showed 0 changes.
> handle more RAPIDS version formats in update-version.sh, refactor dependencies.yaml

- ci/build_wheel_cuspatial.sh
Forward-merge triggered by push to `branch-24.02` that creates a PR to keep `branch-24.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-24.02 to branch-24.04

- python/cuspatial/cuspatial/core/binops/intersection.py
- python/cuspatial/cuspatial/core/geoseries.py
- python/cuspatial/cuspatial/core/spatial/nearest_points.py
- python/cuspatial/cuspatial/core/trajectory.py
- python/cuspatial/cuspatial/tests/basicpreds/test_intersections.py
- python/cuspatial/cuspatial/tests/spatial/bounding/test_linestring_bounding_boxes.py
- python/cuspatial/cuspatial/tests/spatial/join/test_point_in_polygon.py
- python/cuspatial/cuspatial/tests/spatial/nearest_points/test_nearest_points.py
- python/cuspatial/cuspatial/tests/test_geodataframe.py
- python/cuspatial/cuspatial/tests/test_geoseries.py
This PR fixes recent breakage due to pandas 2.2 upgrade.
Fixes #1341.
> Fix Broken CI for 24.04

- conda/recipes/libcuspatial/build.sh
The `-DNVBench_ENABLE_CUPTI=OFF` flag is no longer needed because of https://github.com/rapidsai/rapids-cmake/pull/504. NVBench CUPTI support is now disabled by default.
> Remove -DNVBench_ENABLE_CUPTI=OFF.

- cpp/cuproj/cmake/thirdparty/get_proj.cmake
PROJ doesn't generate export rules in its build dir, so the pip package doesn't find it when using cuPROJ from its build dir.
This PR ensures that configuring the pip package to use `cuPROJ` from its build dir also uses `PROJ` from the `_deps/proj-build` dir.
> write PROJ build dir export rules

- python/cuspatial/cuspatial/tests/test_geodataframe.py
This marks a memory test as `xfail`, which was failing on Python 3.11.
xref: https://github.com/rapidsai/cuspatial/issues/1352
xref: https://github.com/rapidsai/build-planning/issues/3
> Fix Python 3.11 test failures

- ci/test_python.sh
- ci/test_wheel_cuproj.sh
- ci/test_wheel_cuspatial.sh
This PR uses the `worksteal` algorithm to accelerate parallel pytests. See https://github.com/rapidsai/cudf/pull/15207.
> Switch `pytest-xdist` algorithm to `worksteal`

- ci/build_docs.sh
- ci/check_style.sh
- ci/test_cpp.sh
- ci/test_notebooks.sh
- ci/test_python.sh
conda dropped support for the `--force` flag to `conda env create`. This changes that flag name to `--yes`.
See https://github.com/conda/conda/blob/main/CHANGELOG.md#2430-2024-03-12 and https://github.com/rapidsai/miniforge-cuda/pull/63 for more info.
> Use `conda env create --yes` instead of `--force`

- python/cuproj/pyproject.toml
Following https://github.com/rapidsai/build-planning/issues/26, enabled warnings-as-errors for cuproj test
> Enable warnings-as-errors for cuproj tests

- cpp/benchmarks/CMakeLists.txt
- cpp/include/cuspatial/detail/join/quadtree_point_in_polygon.cuh
- cpp/include/cuspatial/detail/range/multilinestring_range.cuh
- cpp/include/cuspatial/geometry/box.hpp
- cpp/include/cuspatial_test/geometry_generator.cuh
- cpp/include/cuspatial_test/vector_factories.cuh
- cpp/tests/CMakeLists.txt
- cpp/tests/join/quadtree_point_in_polygon_test_oom.cu
Followup to https://github.com/rapidsai/cuspatial/pull/1346.
* Fixes some typos/omissions in types and CMake.
* Adds a new test that OOMs when quadtree_point_in_polygon is passed too many input polygons.
* Fixes quadtree spatial join to handle overflow while counting and more conservatively allocate output buffers.
Fixes #890.
* [Failing test run](https://github.com/rapidsai/cuspatial/actions/runs/8979838628/job/24662981350#step:7:840)
* [Passing test run](https://github.com/rapidsai/cuspatial/actions/runs/8981106226/job/24666403165#step:7:840)
> Fix quadtree spatial join OOMs on large numbers of input polygons

- ci/build_docs.sh
- ci/release/update-version.sh
- ci/test_cpp.sh
- ci/test_notebooks.sh
- ci/test_python.sh
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-122_arch-x86_64.yaml
- cpp/benchmarks/CMakeLists.txt
- cpp/include/cuspatial/detail/index/construction/phase_2.cuh
- cpp/include/cuspatial/detail/join/quadtree_point_in_polygon.cuh
- cpp/include/cuspatial/detail/range/multilinestring_range.cuh
- cpp/include/cuspatial/geometry/box.hpp
- cpp/include/cuspatial_test/geometry_generator.cuh
- cpp/include/cuspatial_test/vector_factories.cuh
- cpp/tests/CMakeLists.txt
- cpp/tests/join/quadtree_point_in_polygon_test_oom.cu
- dependencies.yaml
Fixes merge conflicts in https://github.com/rapidsai/cuspatial/pull/1388
> Fix forward-merge `branch-24.06` into `branch-24.08`

- python/cuspatial/cuspatial/tests/basicpreds/test_intersections.py
closes #1395
`pairwise_linestring_intersection`, tested in this file, returns a `cudf.Column` for one of it's arguments and used `to_pandas` to test it's output. in 24.08, the output of `Column.to_pandas` was changed to a `pandas.Index` instead of a `pandas.Series` so modified the test accordingly
> Fix test_intersections.py post cudf refactor

- .devcontainer/cuda11.8-conda/devcontainer.json
- .devcontainer/cuda11.8-pip/devcontainer.json
- .devcontainer/cuda12.2-conda/devcontainer.json
- .devcontainer/cuda12.2-pip/devcontainer.json
Recently devcontainer names were updated to include the current user's name. However, in GitHub Codespaces, the username is not defined. As a result, the container name starts with a dash. This is not allowed by GitHub Codespaces, so it fails to launch.
This PR adds a default value of `anon` to the devcontainer username.
See https://github.com/rapidsai/cudf/pull/15784 for more information.
> Allow anonymous user in devcontainer name

- dependencies.yaml
- python/cuspatial/cuspatial/core/geodataframe.py
- python/cuspatial/cuspatial/tests/spatial/distance/test_pairwise_linestring_distance.py
- python/cuspatial/cuspatial/tests/test_geodataframe.py
- python/cuspatial/cuspatial/tests/test_geoseries.py
An upstream change in cudf uncovered a bug in `_GeoSeriesUtility._from_data` where `False` was being passed to `cudf.Series(index=)` which is an invalid value. The only valid `index` values are an actual `cudf.Index` or `None`, so setting to `None` as a more appropriate default value
Also updates the location of `assert_eq` which moved in https://github.com/rapidsai/cudf/pull/16063
> Change _GeoSeriesUtility._from_data(index=) default to None

- cpp/include/cuspatial/range/multipolygon_range.cuh
- cpp/include/cuspatial_test/vector_factories.cuh
- cpp/tests/range/multipolygon_range_test.cu
This PR fixes a bug in the multipolygon geometry iterator. The geometry iterator was returning part iterators by mistake, which masked an issue that we were patching out in rapids-cmake's CCCL. See https://github.com/rapidsai/rapids-cmake/pull/511.
With this fix, we can remove that patch from rapids-cmake's CCCL: https://github.com/rapidsai/rapids-cmake/pull/640
> Fix multipolygon geometry iterator.

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-122_arch-x86_64.yaml
- conda/recipes/cuproj/conda_build_config.yaml
- conda/recipes/cuspatial/conda_build_config.yaml
- conda/recipes/libcuspatial/conda_build_config.yaml
- dependencies.yaml
- python/cuproj/pyproject.toml
- python/cuspatial/pyproject.toml
Contributes to https://github.com/rapidsai/build-planning/issues/80
Adds constraints to avoid pulling in CMake 3.30.0, for the reasons described in that issue.
> skip CMake 3.30.0

- docs/source/user_guide/cuspatial_api_examples.ipynb
- python/cuspatial/cuspatial/core/geodataframe.py
Exploring notebook fixes with geopandas 1.0.1
> Fix geopandas upgrades

- .gitignore
- ci/test_notebooks.sh
- ci/utils/nbtest.sh
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-122_arch-x86_64.yaml
- dependencies.yaml
- docs/source/user_guide/cuspatial_api_examples.ipynb
- notebooks/nyc_taxi_years_correlation.ipynb
- python/cuspatial/cuspatial/core/geoseries.py
Contributes to #1406.
Unblocks CI.
CI in https://github.com/rapidsai/docker has been failing because of errors in the `cuspatial_api_examples.ipynb` notebook. Specifically, that notebook refers unconditionally to local files that are not guaranteed to exist.
To fix this, that proposes the following:
* in the notebook, conditionally recreate those files if they don't yet exist
* always test the notebooks in `docs/` in CI here
CI **here** is failing because the `nyc_taxi_years_correlation` notebook recently started taking a prohibitively long time to run. This proposes:
* skipping `nyc_taxi_years_correlation` notebook in CI
And some other small things noticed while doing all this:
* fixing typo (`rint -> ring`) and argument ordering in `GeoSeries.from_polygons_xy()` docs
I ran these …
> test notebooks in 'docs/', make cuspatial_api_examples self-contained, skip long-running notebook, fix some docs

- .pre-commit-config.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-122_arch-x86_64.yaml
- dependencies.yaml
With the deployment of rapids-build-backend, we need to make sure our dependencies have alpha specs.
Contributes to https://github.com/rapidsai/build-planning/issues/31
> Use verify-alpha-spec hook

- conda/recipes/cuproj/meta.yaml
- conda/recipes/cuspatial/meta.yaml
Previously `cmake` was added to `requirements/host`. However it is a build tool. So should be placed in `requirements/build`. This makes that change in relevant recipes.
> Conda: Move `cmake` to `requirements/build`

- python/cuspatial/cuspatial/core/binpreds/contains.py
- python/cuspatial/cuspatial/core/geodataframe.py
- python/cuspatial/cuspatial/core/spatial/join.py
- python/cuspatial/cuspatial/core/spatial/nearest_points.py
https://github.com/rapidsai/cudf/pull/16285 makes `_from_data` explicitly requires the `data.values()` to all be a `ColumnBase`. This PR either ensures they are columns or just goes through the normal `GeoDataFrame`/`DataFrame` constructor if they are not.
> Ensure _from_data accepts columns objects only

- dependencies.yaml
- python/cuproj/pyproject.toml
- python/cuspatial/pyproject.toml
Contributes to https://github.com/rapidsai/build-planning/issues/31
In short, RAPIDS DLFW builds want to produce wheels with unsuffixed dependencies, e.g. `cudf` depending on `rmm`, not `rmm-cu12`.
This PR is part of a series across all of RAPIDS to try to support that type of build by setting up CUDA-suffixed and CUDA-unsuffixed dependency lists in `dependencies.yaml`.
For more details, see:
* https://github.com/rapidsai/build-planning/issues/31#issuecomment-2245815818
* https://github.com/rapidsai/cudf/pull/16183
This is targeting 24.08 because:
1. it should be very low-risk
2. getting these changes into 24.08 prevents the need to carry around patches for every library in DLFW builds using RAPIDS 24.08
> split up CUDA-suffixed dependencies in dependencies.yaml

- .devcontainer/cuda12.5-conda/devcontainer.json
- .devcontainer/cuda12.5-pip/devcontainer.json
- .github/workflows/pr.yaml
- .pre-commit-config.yaml
- ci/release/update-version.sh
- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/recipes/cuproj/meta.yaml
- conda/recipes/cuspatial/meta.yaml
- dependencies.yaml
- python/cuproj/pyproject.toml
- python/cuspatial/cuspatial/core/binpreds/contains.py
- python/cuspatial/cuspatial/core/geodataframe.py
- python/cuspatial/cuspatial/core/spatial/join.py
- python/cuspatial/cuspatial/core/spatial/nearest_points.py
- python/cuspatial/pyproject.toml
Resolve conflicts in forward merger: https://github.com/rapidsai/cuspatial/pull/1408
Closes #1416.
> Forward-merge branch-24.08 into branch-24.10

- python/cuspatial/cuspatial/tests/spatial/join/test_point_in_polygon.py
- python/cuspatial/cuspatial/utils/join_utils.py
The performance regression in https://github.com/rapidsai/cuspatial/issues/1413 is due to numba's `DeviceNDArray`
is slow in slicing. Recent cudf's DataFrame construction has simplified the construction and delegated construction
to similar logic that handles __cuda_array_interface__. Since the construction involves slicing the array, we need
this operation to be fast. In that sense, we should cast the use of DeviceNDArray to cupy array to support fast
slicing.
closes #1413
> Use CuPy array in `pip_bitmap_column_to_binary_array`

- python/cuspatial/cuspatial/core/geodataframe.py
closes https://github.com/rapidsai/cuspatial/issues/1427
The API of `cudf.DataFrame.insert` will change in 24.10 to better align with pandas, so adjusting the usage here
xref https://github.com/rapidsai/cudf/pull/16402
> Address cudf.DataFrame.insert API change

- python/cuspatial/cuspatial/core/geodataframe.py
closes https://github.com/rapidsai/cuspatial/issues/1426
It appears there was a change in 24.08 that broke a notebook demonstrating a `merge` on two geometry columns. It seems like the merge result tries to reconstruct a `GeoDataFrame` from a `dict[Any, GeoSeries | Series]` but the `Series.index` alignment requires the types to be recognized cudf types (not `"geometry"`)
I don't think this alignment is entirely necessary though since it goes through the `_split_out_geometry_columns`/`_recombine_columns` methods which appears to be used on operations that maintain row ordering so index alignment isn't required.
This PR instead passes a `dict[Any, GeoColumn | Column]` to `cudf.DataFrame._from_data` given that this row ordering is preserved.
(This PR also includes the fix for …
> Pass columns instead of Series to `cudf.DataFrame` in split-combine workflow

- python/cuspatial/cuspatial/core/_column/geocolumn.py
- python/cuspatial/cuspatial/core/_column/geometa.py
- python/cuspatial/cuspatial/core/binops/distance_dispatch.py
- python/cuspatial/cuspatial/core/binops/equals_count.py
- python/cuspatial/cuspatial/core/binops/intersection.py
- python/cuspatial/cuspatial/core/binpreds/contains.py
- python/cuspatial/cuspatial/core/binpreds/contains_geometry_processor.py
- python/cuspatial/cuspatial/core/binpreds/feature_contains.py
- python/cuspatial/cuspatial/core/binpreds/feature_equals.py
- python/cuspatial/cuspatial/core/binpreds/feature_intersects.py
- python/cuspatial/cuspatial/core/binpreds/feature_touches.py
- python/cuspatial/cuspatial/core/geodataframe.py
- python/cuspatial/cuspatial/core/geoseries.py
- python/cuspatial/cuspatial/core/spatial/distance.py
- python/cuspatial/cuspatial/core/spatial/indexing.py
- python/cuspatial/cuspatial/core/trajectory.py
- python/cuspatial/cuspatial/io/geopandas_reader.py
- python/cuspatial/cuspatial/tests/test_from_geopandas.py
- python/cuspatial/cuspatial/utils/binpred_utils.py
closes #1433
Mirroring the upstream cudf changes in https://github.com/rapidsai/cudf/pull/16454, `cudf.Series` disallows accepting a `ColumnBase` in favor of the `cudf.Series._from_column` constructor. This PR does the same for `GeoSeries` as well as addresses the breakages due to the upstream cudf change.
> Disallow GeoSeries from accepting a column in favor of `_from_column`

- python/cuspatial/cuspatial/core/geodataframe.py
closes https://github.com/rapidsai/cuspatial/issues/1437
When `GeoDataFrame._split_out_geometry_columns` is called, there may be no geometry columns to split out into 2 DataFrames; therefore, once `GeoDataFrame._recombine_columns`, it assumed the 2 DataFrames were always non-empty. Added a check to bypass this validation if either was empty.
I ran the `ZipCodes_Stops_PiP_cuSpatial` notebook locally and the (non-commented) cells no longer raise an exception.
> Fix _recombine_columns when either geocolumn or non-geocolumn was empty

- python/cuspatial/cuspatial/core/_column/geocolumn.py
- python/cuspatial/cuspatial/core/geodataframe.py
With https://github.com/rapidsai/cudf/pull/16549, `cudf.Index` no longer accepts `Column` objects.
The only usage I found was that `GeoColumn` accepted `shuffle_order=cudf.Index(column)`, but `shuffle_order` appears unused (anymore?) in `GeoColumn`, so I went ahead and removed this from the constructor
> Remove unused shuffle_order in GeoColumn

- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- cpp/include/cuspatial/cuda_utils.hpp
- cpp/include/cuspatial/detail/distance/hausdorff.cuh
- cpp/include/cuspatial/detail/find/find_and_combine_segment.cuh
- cpp/include/cuspatial/detail/find/find_duplicate_points.cuh
- cpp/include/cuspatial/detail/intersection/linestring_intersection_count.cuh
- cpp/include/cuspatial/detail/intersection/linestring_intersection_with_duplicates.cuh
- cpp/include/cuspatial/detail/kernel/pairwise_distance.cuh
- cpp/include/cuspatial/detail/pairwise_multipoint_equals_count.cuh
- cpp/include/cuspatial/detail/point_linestring_nearest_points.cuh
- cpp/include/cuspatial_test/geometry_generator.cuh
- cpp/tests/operators/linestrings_test.cu
- cpp/tests/range/multilinestring_range_test.cu
- cpp/tests/range/multipoint_range_test.cu
- cpp/tests/range/multipolygon_range_test.cu
Mark all cuspatial CUDA kernels with internal linkage to avoid runtime symbol collisions.
Also updated the CI tests to also verify that we add no new CUDA kernel with external linkage.
> Internal linkage kernels

- README.md
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- dependencies.yaml
- pyproject.toml
- python/cuproj/pyproject.toml
- python/cuspatial/pyproject.toml
Contributes to https://github.com/rapidsai/build-planning/issues/88
Finishes the work of dropping Python 3.9 support.
This project stopped building / testing against Python 3.9 as of https://github.com/rapidsai/shared-workflows/pull/235.
This PR updates configuration and docs to reflect that.
Checked that there were no remaining uses like this:
```shell
git grep -E '3\.9'
git grep '39'
git grep 'py39'
```
And similar for variations on Python 3.8 (to catch things that were missed the last time this was done).
> Drop Python 3.9 support

- README.md
- ci/test_wheel_cuproj.sh
- ci/test_wheel_cuspatial.sh
RAPIDS libraries recently started running nightly wheel tests on Rocky Linux 8: https://github.com/rapidsai/shared-workflows/pull/236/files#r1725947245
That distribution's system package manager is `yum`, not `apt`, and as a result `cuspatial`'s nightly runs are failing like this:
```text
ci/test_wheel_cuspatial.sh: line 10: apt: command not found
Error: Process completed with exit code 127.
```
([build link](https://github.com/rapidsai/cuspatial/actions/runs/10678284262/job/29595047179))
This fixes that.
```shell
docker run \
--rm \
--gpus 1 \
-v $(pwd):/opt/work \
-w /opt/work \
-it rapidsai/citestwheel:cuda12.5.1-rockylinux8-py3.11 \
bash
yum update -y
yum config-manager --set-enabled powertools
yum update -y
yum install -y gdal-devel
python -m pip install \
--no-binary fiona \ …
```
> fix wheel tests on Rocky Linux

- python/libcuspatial/libcuspatial/load.py
Fixes #1455
devcontainer conda CI jobs are failing in this project because of the following mix of characteristics for thoes jobs:
* all build and runtime dependencies for `libcuspatial`, `cuspatial`, `cuproj` are installed via conda
* `libcuspatial`, `cuspatial`, and `cuproj` wheels are then built with `pip install -e --no-deps --no-build-isolation`
* `import libcuspatial` results in unconditionally running `import libcudf`
* `libcudf` is provided by the `libcudf` **conda** package, which does not have any Python modules, so that import fails
This fixes that, and restores the ability to mix a `pip install`'d `cuspatial` / `cuproj` with a `conda`-installed `libcudf`.
When https://github.com/rapidsai/devcontainers/pull/387 was merged, I only re-ran the **pip** devcontainers CI job on …
> re-enable mixing libcuspatial wheels with libcudf conda packages

- .pre-commit-config.yaml
- python/cuspatial/cuspatial/tests/test_geodataframe.py
- python/cuspatial/cuspatial/tests/test_geoseries.py
We need to update flake8 to fix a false-positive that appears with older flake8 versions on Python 3.12.
> Update flake8 to 7.1.1.

- python/cuproj/cuproj/tests/pytest.ini
- python/cuspatial/cuspatial/tests/pytest.ini
In cudf & cuml we have observed a ~10% to ~20% respectively speed up of pytest suite execution by switching pytest traceback to `--native`:
```
currently:
102474 passed, 2117 skipped, 902 xfailed in 892.16s (0:14:52)
--tb=short:
102474 passed, 2117 skipped, 902 xfailed in 898.99s (0:14:58)
--tb=no:
102474 passed, 2117 skipped, 902 xfailed in 815.98s (0:13:35)
--tb=native:
102474 passed, 2117 skipped, 902 xfailed in 820.92s (0:13:40)
```
This PR makes similar change to `cuspatial` repo.
xref: https://github.com/rapidsai/cudf/pull/16851
> Switch `traceback` to `native` in pytests

- python/cuspatial/cuspatial/tests/conftest.py
- python/cuspatial/cuspatial/tests/test_cudf_integration.py
- python/cuspatial/cuspatial/tests/test_geodataframe.py
Appears the `gs` fixture in the `conftest.py` contains invalid polygon (the holes are beyond shell), and geos 3.13 now does not consider the same invalid polygon equivalent https://github.com/libgeos/geos/issues/1177.
The `gs` fixture and the `polys` fixture (which is hard-coded) need to both be updated, but I wasn't able to get a quick-working fix (I'm not familiar with this area). This PR just xfails the effected tests.
> xfail Python tests dependent on invalid Polygons

- ci/build_docs.sh
- ci/release/update-version.sh
Contributes to https://github.com/rapidsai/build-planning/issues/106
This project doesn't need any of the changes that are being made as part of that issue across most other repos... it's already doing all of its `pip` and `conda` installs in CI in single installs (which is strict and safe) 🎉 
This small PR just makes its handling of environment variables in `ci/build_docs.sh` consistent with other RAPIDS repos, in the interest of keeping those scripts looking similar so it's easy to apply changes across all RAPIDS projects. ref: https://github.com/rapidsai/cudf/pull/17013#discussion_r1792163289
> remove unused variables in build_docs script

- README.md
A few minor documentation updates to align with the rest of RAPIDS.
> Update README architecture and platform support

- python/cuspatial/cuspatial/utils/column_utils.py
https://github.com/rapidsai/cudf/pull/16715 makes size 0 cudf columns have no mask buffer which I think aligns with the intention in `empty_geometry_column`. Additionally, it makes the `masked` keyword unnecessary and unused so removing it here.
> Remove unused masked keyword in column_empty

- cpp/cmake/Modules/ConfigureCUDA.cmake
Fixes #1501.
Restores removed `--expt-relaxed-constexpr` for libcuspatial
> Restore removed `--expt-relaxed-constexpr`

- .pre-commit-config.yaml
- dependencies.yaml
- docs/source/developer_guide/contributing_guide.md
Removes references to `setup.cfg` and `versioneer` in the contributing docs... `cuspatial` no longer uses either of these.
Also updates `rapids-dependency-file-generator` to its latest version (v1.17.0) and removes an unused YAML anchor in `dependencies.yaml`.
> remove versioneer and setup.cfg references in docs, update rapids-dependency-file-generator

- cpp/cuproj/README.md
- cpp/cuproj/doxygen/main_page.md
- cpp/cuproj/tests/wgs_to_utm_test.cu
This fixes libcuproj documentation example inconsistencies raised in #1500.
It removes the (outdated) example from the doxygen `main_page` and replaces it with a link to the readme.
It also makes the type definitions simpler in the README example and makes the Test code match the example.
> Fix libcuproj doc example and make tests consistent.

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/recipes/cuproj/conda_build_config.yaml
- conda/recipes/cuproj/meta.yaml
- conda/recipes/cuspatial/conda_build_config.yaml
- conda/recipes/cuspatial/meta.yaml
- conda/recipes/libcuspatial/conda_build_config.yaml
- conda/recipes/libcuspatial/meta.yaml
- dependencies.yaml
conda-forge is using GCC 13 for CUDA 12 builds. This PR updates CUDA 12 conda builds to use GCC 13, for alignment.
These PRs should be merged in a specific order, see https://github.com/rapidsai/build-planning/issues/129 for details.
> Use GCC 13 in CUDA 12 conda builds.

- python/cuspatial/cuspatial/_lib/distance.pyx
- python/cuspatial/cuspatial/_lib/intersection.pyx
- python/cuspatial/cuspatial/_lib/linestring_bounding_boxes.pyx
- python/cuspatial/cuspatial/_lib/nearest_points.pyx
- python/cuspatial/cuspatial/_lib/pairwise_multipoint_equals_count.pyx
- python/cuspatial/cuspatial/_lib/pairwise_point_in_polygon.pyx
- python/cuspatial/cuspatial/_lib/point_in_polygon.pyx
- python/cuspatial/cuspatial/_lib/points_in_range.pyx
- python/cuspatial/cuspatial/_lib/polygon_bounding_boxes.pyx
- python/cuspatial/cuspatial/_lib/quadtree.pyx
- python/cuspatial/cuspatial/_lib/spatial.pyx
- python/cuspatial/cuspatial/_lib/spatial_join.pyx
- python/cuspatial/cuspatial/_lib/trajectory.pyx
- python/cuspatial/cuspatial/_lib/utils.pyx
- python/cuspatial/cuspatial/core/binops/distance_dispatch.py
- python/cuspatial/cuspatial/core/binops/equals_count.py
- python/cuspatial/cuspatial/core/binops/intersection.py
- python/cuspatial/cuspatial/core/binpreds/contains.py
- python/cuspatial/cuspatial/core/spatial/bounding.py
- python/cuspatial/cuspatial/core/spatial/distance.py
- python/cuspatial/cuspatial/core/spatial/filtering.py
- python/cuspatial/cuspatial/core/spatial/indexing.py
- python/cuspatial/cuspatial/core/spatial/join.py
- python/cuspatial/cuspatial/core/spatial/nearest_points.py
- python/cuspatial/cuspatial/core/spatial/projection.py
- python/cuspatial/cuspatial/core/trajectory.py
Related to https://github.com/rapidsai/cudf/issues/17317, it appears the Cython bindings are not dependent on any methods specifically on `cudf._lib.column.Column`. It appears most routines operate on `column_view` which can be provided by a `pylibcudf.Column`.
This PR essentially makes the routines defined in Cython accept a `pylibcudf.Column` instead and return a `cudf.core.column.Column` object instead (which should help cudf transition away from its `cudf._lib.column.Column`)
> Have Cython methods accept pylibcudf.Column instead of cudf._lib.column.Column

- .pre-commit-config.yaml
- ci/build_docs.sh
- ci/build_python.sh
- ci/build_wheel.sh
- ci/build_wheel_cuspatial.sh
- ci/check_style.sh
- ci/release/update-version.sh
- ci/test_cpp.sh
- ci/test_notebooks.sh
- ci/test_wheel_cuproj.sh
- ci/test_wheel_cuspatial.sh
- ci/utils/nbtest.sh
- ci/validate_wheel.sh
`shellcheck` is a fast, static analysis tool for shell scripts. It's good at
flagging up unused variables, unintentional glob expansions, and other potential
execution and security headaches that arise from the wonders of `bash` (and
other shlangs).                   
This PR adds a `pre-commit` hook to run `shellcheck` on all of the `sh-lang`
files in the `ci/` directory, and the changes requested by `shellcheck` to make
the existing files pass the check.                              
xref: rapidsai/build-planning#135
> Add shellcheck to pre-commit and fix warnings

- python/cuspatial/cuspatial/_lib/distance.pyx
- python/cuspatial/cuspatial/_lib/intersection.pyx
- python/cuspatial/cuspatial/_lib/linestring_bounding_boxes.pyx
- python/cuspatial/cuspatial/_lib/nearest_points.pyx
- python/cuspatial/cuspatial/_lib/pairwise_multipoint_equals_count.pyx
- python/cuspatial/cuspatial/_lib/pairwise_point_in_polygon.pyx
- python/cuspatial/cuspatial/_lib/point_in_polygon.pyx
- python/cuspatial/cuspatial/_lib/points_in_range.pyx
- python/cuspatial/cuspatial/_lib/polygon_bounding_boxes.pyx
- python/cuspatial/cuspatial/_lib/quadtree.pyx
- python/cuspatial/cuspatial/_lib/spatial.pyx
- python/cuspatial/cuspatial/_lib/spatial_join.pyx
- python/cuspatial/cuspatial/_lib/trajectory.pyx
- python/cuspatial/cuspatial/core/binops/distance_dispatch.py
- python/cuspatial/cuspatial/core/binops/equals_count.py
- python/cuspatial/cuspatial/core/binops/intersection.py
- python/cuspatial/cuspatial/core/binpreds/contains.py
- python/cuspatial/cuspatial/core/spatial/bounding.py
- python/cuspatial/cuspatial/core/spatial/distance.py
- python/cuspatial/cuspatial/core/spatial/filtering.py
- python/cuspatial/cuspatial/core/spatial/indexing.py
- python/cuspatial/cuspatial/core/spatial/join.py
- python/cuspatial/cuspatial/core/spatial/nearest_points.py
- python/cuspatial/cuspatial/core/spatial/projection.py
- python/cuspatial/cuspatial/core/trajectory.py
Follow up to https://github.com/rapidsai/cuspatial/pull/1514
Addressing the review in https://github.com/rapidsai/cuspatial/pull/1514#discussion_r1927600686 by ensuring the Cython bindings return pylibcudf objects where possible instead of python objects (like cudf Python columns) so we can also have better return annotations for these methods where appropriate. Subsequently, the conversion from pylibcudf to cudf Python has been moved to the cuspatial Python layer.
Additionally, this PR will be necessary for https://github.com/rapidsai/cudf/pull/17760 not to break cuspatial
> Ensure Cython bindings only interact with pylibcudf objects

- .github/workflows/pr.yaml
- python/cuspatial/cuspatial/_lib/distance.pyx
- python/cuspatial/cuspatial/_lib/intersection.pyx
- python/cuspatial/cuspatial/_lib/linestring_bounding_boxes.pyx
- python/cuspatial/cuspatial/_lib/nearest_points.pyx
- python/cuspatial/cuspatial/_lib/pairwise_multipoint_equals_count.pyx
- python/cuspatial/cuspatial/_lib/pairwise_point_in_polygon.pyx
- python/cuspatial/cuspatial/_lib/point_in_polygon.pyx
- python/cuspatial/cuspatial/_lib/points_in_range.pyx
- python/cuspatial/cuspatial/_lib/polygon_bounding_boxes.pyx
- python/cuspatial/cuspatial/_lib/quadtree.pyx
- python/cuspatial/cuspatial/_lib/spatial.pyx
- python/cuspatial/cuspatial/_lib/spatial_join.pyx
- python/cuspatial/cuspatial/_lib/trajectory.pyx
- python/cuspatial/cuspatial/core/binops/distance_dispatch.py
- python/cuspatial/cuspatial/core/binops/equals_count.py
- python/cuspatial/cuspatial/core/binops/intersection.py
- python/cuspatial/cuspatial/core/binpreds/contains.py
- python/cuspatial/cuspatial/core/spatial/bounding.py
- python/cuspatial/cuspatial/core/spatial/distance.py
- python/cuspatial/cuspatial/core/spatial/filtering.py
- python/cuspatial/cuspatial/core/spatial/indexing.py
- python/cuspatial/cuspatial/core/spatial/join.py
- python/cuspatial/cuspatial/core/spatial/nearest_points.py
- python/cuspatial/cuspatial/core/spatial/projection.py
- python/cuspatial/cuspatial/core/trajectory.py
Addressing merge conflict in https://github.com/rapidsai/cuspatial/pull/1530
> Forward-merge branch-25.02 into branch-25.04

- ci/build_wheel.sh
- ci/build_wheel_libcuspatial.sh
- ci/test_wheel_cuproj.sh
- ci/test_wheel_cuspatial.sh
Uses a retry wrapper for `pip` commands to try to alleviate CI failures due to hash mismatches that result from network hiccups
xref rapidsai/build-planning#148
This will retry failures that show up in CI like:
```
Collecting nvidia-cublas-cu12 (from libraft-cu12==25.2.*,>=0.0.0a0)
Downloading https://pypi.nvidia.com/nvidia-cublas-cu12/nvidia_cublas_cu12-12.8.3.14-py3-none-manylinux_2_27_aarch64.whl (604.9 MB)
━━━━━━━━━━━━━━━━━━━━━                 350.2/604.9 MB 229.2 MB/s eta 0:00:02
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
nvidia-cublas-cu12 from …
```
> Use `rapids-pip-retry` in CI jobs that might need retries

- cpp/include/cuspatial/detail/distance/linestring_distance.cuh
- cpp/include/cuspatial/detail/distance/point_linestring_distance.cuh
- cpp/include/cuspatial/detail/functors.cuh
- cpp/include/cuspatial/detail/kernel/pairwise_distance.cuh
- cpp/include/cuspatial/detail/range/enumerate_range.cuh
- cpp/include/cuspatial/detail/range/multilinestring_range.cuh
- cpp/include/cuspatial/detail/utility/linestring.cuh
- cpp/include/cuspatial/range/multilinestring_range.cuh
- cpp/include/cuspatial/traits.hpp
- cpp/include/cuspatial_test/test_util.cuh
- cpp/tests/operators/linestrings_test.cu
Its deprecated and will be removed in a future CCCL release
> Replace `thrust::optional` with `cuda::std::optional`

- cpp/cuproj/cmake/patches/proj.patch
- cpp/cuproj/cmake/patches/proj_override.json
- cpp/cuproj/cmake/thirdparty/get_proj.cmake
This is interfering with other projects that also have an uninstall target.
> Patch PROJ to remove uninstall target

- python/cuspatial/cuspatial/core/_column/geocolumn.py
- python/cuspatial/cuspatial/core/binops/distance_dispatch.py
- python/cuspatial/cuspatial/core/binops/intersection.py
- python/cuspatial/cuspatial/core/geoseries.py
- python/cuspatial/cuspatial/core/spatial/join.py
- python/cuspatial/cuspatial/core/spatial/nearest_points.py
- python/cuspatial/cuspatial/core/trajectory.py
- python/cuspatial/cuspatial/utils/column_utils.py
https://github.com/rapidsai/cudf/pull/17978 required dtype objects to be passed around when converting types of cuDF column (to avoid overhead of parsing dtype strings).
This PR aligns with that change by passing dtype objects when calling `as_column`
> Pass dtype objects to cudf as_column calls

- cpp/cuproj/cmake/patches/proj.patch
- cpp/cuproj/cmake/patches/proj_override.json
- cpp/cuproj/cmake/thirdparty/get_proj.cmake
The `conda` devcontainer is building fine with `proj` 9.6.0, but the `pip` one
is failing because of cmake version restrictions on 9.2.0 -- this bumps the
version of `proj` we pull down via `cpm` and updates the patch to remove the
uninstall target.
> fix(proj): update patch to version 9.6.0
